### ISSUE TITLE
Custom settings for Search view

### ISSUE THREAD

**Issue by SumatraPeter** [LesFerch/WinSetView#10]
Is it possible to have custom settings for Search view as opposed to normal folder view? For example a column like Folder Path would be very useful in Search view to indicate the exact location of each result, but I don't want it showing up and wasting space in normal Details view while browsing through a folder.

**Comment by LesFerch** [comment]
Thanks for writing Peter. I look forward to discussing possible
enhancements to the script.

Settings and backup files location...

That brings into play Windows programming standards and user rights.
Regular (non-admin) users cannot write everywhere. Using the Roaming folder
means it works for all users (and moves with users in an Active Directory
domain). Off the top of my head, I could have it write everything to a
folder at the same location as the script and go to the Roaming folder if
the user has no write access. But...that may be a confusing change. I might
make it a switch, so you can have it work one way or the other. Have to
think about it...

Specific view settings for Search results...

Yes, this is something I've been actively looking into and will add to the
feature request list. I'm pretty certain there's no technical barrier. But,
it's going to be a major challenge to work it into the interface. I'm not
fast. It's probably a solid two weeks of work for me (which could be months
in real time), but I do see the benefit, so I will try.

Features 2, 4, and 6...

#2 (Recycle Bin default view), I always thought the Windows default made a
lot of sense (i.e. Details with "Original Location" and "Date Deleted"
columns). What would you change for the default? I'm assuming you don't
want it the same as every other folder, or do you?

#4 (Default sort order/columns) I figured most people would want the
Windows default of sort by Name as a global default. So, I need to get more
input to figure out if there's any easy solution. Providing options to
select any column and any sort order will require a major rewrite. What
sort order/columns were you wanting?

#6 (More column widths) This one will also require a major rewrite to add
it to the interface. But maybe there's something I can add for power users,
such as an INI file where you can specify column names and widths. I
suppose the same INI file could also be used for sort order. Just
brain-storming here...

In the meantime, are all of these extra settings for views you want
globally, or do some of them apply only to specific folder types, such as
Pictures, Music, Videos, etc?

Les

P.S. By Winter, I mean late 2021 to early 2022. Right now, I should be
renovating another house, but the sale is held up with some issues on the
seller's side, so I might have a bit more time to tinker... ;)

**Comment by SumatraPeter** [comment]
Thanks, look forward to it being implemented.

**Comment by LesFerch** [comment]
I've made some progress. I hope to have something ready to test in a day or two.

**Comment by LesFerch** [comment]
I decided to do a new interface that will allow setting views for all major folder types, select any column, set column widths, and set primary and secondary sort columns and order. So, it's going to be a bit longer to get this issue resolved. Maybe another week or two. In the meantime, I posted a workaround to get a path column only in search results in the Readme.

**Comment by LesFerch** [comment]
I just posted WinSetView 1.5 to the main branch. This version applies any selected path columns to search results only. So, if you select, for example "Folder path", that column will not appear when browsing, but will appear when you do a search. Version 1.5 also fixes an issue with incorrect columns being displayed in Library views.

For now, version 1.5 is only in the main branch. I'll wait a bit before doing a release to be sure everything is OK.

**Comment by LesFerch** [comment]
@SumatraPeter Have you tried version 1.50 yet?

**Comment by DragKnuckle** [comment]
It's great, thanks for creating this and sharing it with us, I've learned quite a bit figuring out how it works. I am still somewhat dumbstruck that MS made this so difficult, who would have thought that it was such short leap from UI designer to forensic investigator?

**Comment by LesFerch** [comment]
Indeed. Today I spent some time trying to figure out some of the odder Explorer column headings, such as "Categories", "Link Status", and three different headings named "Status". And then there's the weird FileItemAPIs FolderType and the ColumnList items in the registry that start with "2" that appear to do nothing.

**Comment by LesFerch** [comment]
WinSetView v2 is now posted. It includes many new features, including custom settings for search views.
