### ISSUE TITLE
where is new compiled executable?

### ISSUE THREAD

**Issue by Skrell** [LesFerch/WinSetView#100]
where is new compiled executable?

**Comment by LesFerch** [comment]
Are you referring to the fact that there was a recent update, but no version number change?

**Comment by LesFerch** [comment]
Are you referring to the fact that there was a recent update, but no version number change?
Or are you referring to the fact that the Release page only appears to have "source code"?

The recent minor change was one line in the PowerShell script that only affects users that select the "Legacy row and icon spacing" option (aka WIndows Vista view mode).

The Release page is correct. This package has the exe included in the source code. That's unusual, but it's related to it originally being an HTA script. Anyhow, whether you use the download link in the ReadMe or the zip file from the release page, you'll get the same package.

**Comment by Skrell** [comment]
got it ty!

**Comment by LesFerch** [comment]
👍
