### ISSUE TITLE
Some apps might save per-app view, ignoring templates?

### ISSUE THREAD

**Issue by maxwowpow** [LesFerch/WinSetView#103]
`search` in the `opendialog` view not showing `details` in the `SYMENU` APP

<img width="696" alt="2024-03-27 01_46_16-Select file" src="https://github.com/LesFerch/WinSetView/assets/169885/af7f039e-4786-4bf5-a653-e832c86ac4da">

**Comment by LesFerch** [comment]
It looks like you're in a file open/save dialog of an application. Is that correct? If so, the usual explanation is that app was open when you ran WinSetView. Logout and login and then try WinSetView again. If the problem persists, let me know what app that is. And try the search from a regular Explorer window to confirm you get the expected view there.

**Comment by maxwowpow** [comment]
## search from
  * explorer -> OK (detail view)
  * `opendialog` in many apps -> OK (detail view), including running before `WinSetView` was run.

## the app is `SyMenu`
  * restart of the app -> FAIL (still not detail view).
  * todo: relogin test follows.

## notes
  - maybe connected to the specific "Gallery" folder
  - [
<img width="241" alt="2024-03-27 02_31_32-Gallery" src="https://github.com/LesFerch/WinSetView/assets/169885/70c928cc-2d91-49e7-a7f4-d32d652794c7">
](url)
  - the search in the explorer in the gallery directly works as expected though.
  - `SyMenu`: go to Configuration > add an App -> browse for an exe or an icon.
  - when setting this funny collection-view to details manually, it preserves the selection. Maybe the app serialized somehow the view of the dialog in its config and the "global" template (what is being set by the `WSV (c)`) not used at all. Because the app even persists the `search TERM` one used last time.

**Comment by LesFerch** [comment]
The view shown is just the Windows default search result layout. You must have previously did a search before running WinSetView which created a saved view in the registry for that folder. WinSetView would have deleted all the saved views, but some app (maybe SyMenu, but not necessarily) had that view open with the old default view which then created a new saved view with the old default settings.

Do a logout and login (or restart) and then run WinSetView before running anything else. That should work. Let me know if that resolves it.

**Comment by LesFerch** [comment]
If the problem persists, I would suspect some software that is restoring saved views on login, such as [WindowManager](https://www.ghacks.net/2018/08/12/windowmanager-remember-window-sizes-and-positions-in-windows/).

**Comment by LesFerch** [comment]
Just checking back. Did you get this sorted?

**Comment by maxwowpow** [comment]
I log out not that often because of the logistical reasons. Let's close it and reopen if there are any other troubles.

**Comment by LesFerch** [comment]
The issue may have occurred for apps that don't actually close when you click the close box.

Apps that minimize to the System Tray when "closed", such as Discord, Steam, and qBittorrent, must be fully closed (e.g. right-click the app’s System Tray icon and select `Exit`).
