### ISSUE TITLE
Gramattical error in Help for  (Column Width)

### ISSUE THREAD

**Issue by KangOdoo** [LesFerch/WinSetView#113]
https://lesferch.github.io/WinSetView/Manual.html

Please note that you can set the width as small as 1em, but Explorer will expand the column width to it’s minimum allowed value when you drag the column width control in Explorer Details view. The minimum value cannot be overridden.

s/b

Please note that you can set the width as small as 1em, but Explorer will expand the column width to its minimum allowed value when you drag the column width control in Explorer Details view. The minimum value cannot be overridden.

**Comment by LesFerch** [comment]
Fixed (there and a few other places). Thank you! 🙂
