### ISSUE TITLE
Context menu is normal in browsing, but classic in open/save dialogs

### ISSUE THREAD

**Issue by AlicesWrath** [LesFerch/WinSetView#115]
Hi,
I was hoping you could help, I'm not sure if this is even a WinSetView thing or a Windows bug or something else is causing this, but I'm having a strange problem with the context menu.
When regularly browsing files and folders, it uses the modern Win11 context menu, however when I right click while in a Open or Save as dialog, it uses the classic context menu for some reason.
I included screenshots of the behaviour below and also included my WinSetView options showing classic context menu is not checked.

![Untitled](https://github.com/LesFerch/WinSetView/assets/6634484/43f992d0-d5ad-4baf-bfae-e9877ea90c4a)
![Screenshot 2024-07-08 003241](https://github.com/LesFerch/WinSetView/assets/6634484/c89092ac-a5e1-4f56-83a6-91af79dddba4)
![Screenshot 2024-07-08 003409](https://github.com/LesFerch/WinSetView/assets/6634484/63a2022c-25a3-4974-aa14-1329dfe5e4a1)

Like I said, I don't know if WinSetView is causing this but I have no idea what else it could be. Have I accidentally changed some registry value?

**Comment by LesFerch** [comment]
That's the normal behavior for Windows 11. Only Explorer itself has the new interface. The file open/save dialogs, that are used by applications, are a separate interface that shares some Explorer resources (such as the folder view registry entries). Note that the file open/save dialogs look much more like the Windows 10 Explorer than the Windows 11 Explorer.

It's possible that Microsoft will, some day, create a new file open/save dialog that looks like the new Explorer (and use the new context menu) but that will only be applicable to new or updated apps that choose to use it. If they change the code that's used by existing apps, it will cause things to break.

We've seen the file open/save dialog interface change before. You can observe this by opening RegEdit and selecting Export from the File menu. That will open a "legacy" dialog. You can see the same thing in some apps, such as IrfanView. Some day the current file open/save dialogs may become known as "legacy" dialogs, but for now, there is nothing newer.
