### ISSUE TITLE
WinSetView v2.97 Script error

### ISSUE THREAD

**Issue by ericgl** [LesFerch/WinSetView#118]
![image](https://github.com/user-attachments/assets/eb24b167-0e93-49ed-b453-07085fc8ab25)

**Comment by LesFerch** [comment]
That's where it runs GetMoreProperties.exe to dynamically read in all additional third-party properties. The line immediately before that checks for the existence of the file GetMoreProperties.exe before trying to execute it, to try to avoid such an error. The only explanation that comes to mind is that your AV software quarantined that executable at that point of execution. What AV software do you have?

**Comment by ericgl** [comment]
Windows Security. Not using a 3rd party AV.

**Comment by AllanHigdon** [comment]
I had the same error.
Even if I change the file properties of WinSetView.exe to Run as Administrator, this error still occurs.
The previous version had no problem being located in %ProgramFiles(x86)%\WinSetView.

**Comment by LesFerch** [comment]
Thanks. I get the same error when it's placed in Program Files (x86). I'll fix that and post an update later today.

**Comment by LesFerch** [comment]
The error occurs in 2.97 if it's located in any folder that contains a space. That was a stupid oversight on my part. My testing procedures normally include testing with a path that contains spaces. I managed to forget to do that with 2.97. 😳

It's all fixed now in 2.98.
