### ISSUE TITLE
Size all columns to fit 

### ISSUE THREAD

**Issue by Raynbda** [LesFerch/WinSetView#123]
Is it possible to add "Size all columns to fit" option that you get by right clicking the columns on file explorer to winsetview

**Comment by LesFerch** [comment]
No. The “Size All Columns to Fit” button is an action that only occurs when you click that button. It's not a setting or a state. See my reply about this [here](https://www.reddit.com/r/WindowsHelp/comments/18y50qo/permanent_global_autofitting_of_explorer_column/).
