### ISSUE TITLE
[Feature Request] Add support for deploying WinSetView through WinGet

### ISSUE THREAD

**Issue by Akaizoku** [LesFerch/WinSetView#124]
> What about winget? It comes with windows.

I recommend opening a new issue. I'll mark it as an enhancement and may look at it someday, but it would be nice to get some help to create a WinGet package.

The last time this came up, a user created a WinGet package for WinSetView following the guidelines for a portable app and there was an issue. Those guidelines apparently required the use of a **symlink** instead of a **shortcut**. But a symlink won't work correctly from a Cmd or PowerShell prompt. It works fine when double-clicked or executed via the Run menu. If this is accurate, I think it was a very silly idea for the powers that be to insist on a symlink. If they still have that requirement, then a WinGet package for WinSetView (and any portable app you wish to run from the command line) will be at least partially broken.

_Originally posted by @LesFerch in https://github.com/LesFerch/WinSetView/issues/107#issuecomment-2308897499_

**Comment by Akaizoku** [comment]
While users report issues in Windows 10, it appears to work out of the box in Windows 11.

**Comment by LesFerch** [comment]
The WinSetView repository now includes an installer, `WinSetView-Setup.exe`, created with Inno Setup. This may now be used to create a reliable WinGet package.

**Comment by kris6673** [comment]
@LesFerch If possible, please don't replace the installer file after you have made a Github release. It breaks installing via winget(and choco), as the installer it expects, is not the one it finds at the download location. Therefore the installation fails with a "installer hash mismatch".  
If you have small fixes, please make them as a new minor release, then I will get notified about it :)

**Comment by LesFerch** [comment]
Ah, sorry, I missed your previous message stating that a package had been made. I'll increment the most minor version number going forward when there are trivial changes.

**Comment by kris6673** [comment]
> Ah, sorry, I missed your previous message stating that a package had been made. I'll increment the most minor version number going forward when there are trivial changes.

Thank you, I'll try my best to keep it up to date :)

**Comment by LesFerch** [comment]
Did you update the package yet? I just tried and got a hash error, so I guess not.

**Comment by kris6673** [comment]
> Did you update the package yet? I just tried and got a hash error, so I guess not.

Yep, had to be approved and merged first. That can take anywhere from a few hours to a day :)  
Should be working now!

**Comment by kris6673** [comment]
@LesFerch Confirmed it to work now. 
Can leave up the previous releases too?

**Comment by kris6673** [comment]
> I assume it's ok to delete the release as long as I leave the **tag** (since that's the container for the files). Correct?

I'd assume yes, but honestly not sure, I think you need to leave it all up casue when I look at the 3.0.0 release the installer is gone from there
https://github.com/LesFerch/WinSetView/releases/tag/3.0.0

**Comment by LesFerch** [comment]
Yes, I see. The tag keeps the source code, but not the binaries. I'll have to leave the complete release in place.
