### ISSUE TITLE
Apply changes to Photoshop legacy save as / open dialog boxes

### ISSUE THREAD

**Issue by awadrummer** [LesFerch/WinSetView#125]
The changes work for Windows Explorer windows, but the dialog boxes in Photoshop do not respect the changes. They do change in Photoshop, just not the same way as in Windows Explorer.

**Comment by LesFerch** [comment]
Is there any chance PhotoShop was still open when you ran WinSetView? Could it have still been running as a background process?

**Comment by LesFerch** [comment]
I tested PhotoShop 2023 and saw no problem at all. Even with PhotoShop open, the file open/save dialog view was changed to what I set in WinSetView.

Are you sure you don't have a separate view set for file dialogs in WinSetView? For example:

![image](https://github.com/user-attachments/assets/9368231f-a7ac-4dea-a25e-d74d719ff7f8)

**Comment by LesFerch** [comment]
Also note that the file dialogs use code that provides a look and feel that is the same as the Windows 10 Explorer.

The Windows 11 Explorer has an updated look that only applies to Explorer. File dialogs retain the old style.

**Comment by LesFerch** [comment]
If you're still having an issue, please post a screenshot.

**Comment by LesFerch** [comment]
Closing. Can't duplicate. No replies from OP.
