### ISSUE TITLE
Use PowerShell registry functions to work around "Registry editing has been disabled by your administrator" 

### ISSUE THREAD

**Issue by dkaszews** [LesFerch/WinSetView#127]
I love this program for fixing the views on all my Windows devices, unfortunately it does not work on some of my work PCs due to regedit being blocked by group policy.

I have been able to edit registry settings with the `Set-ItemProperty HKLM:/...`, so this should be fixable by porting all `& $RegExe` lines to appropriate cmdlets:

* `Query` => `Get-(Child)Item`
* `Add` => `New/Set-Item(Property)`
* `Delete` => `Remove-Item(Property)`

Unsure how to deal with import/export, but it looks to me  like they are mostly used for manipulating keys in text form, which could be done with a powershell dict instead. A backup and restore could be done by storing said dict as JSON.

**Comment by LesFerch** [comment]
Re-coding and, most importantly, thoroughly testing, a change of all the registry edits to use PowerShell commands will be a lot of work. Probably on the order of dozens of hours (it has to work on Windows 7 - 11 and 32 and 64 bit). Some of the edits are done by building a reg file and then importing that file. Changing that code to pure PowerShell will be challenging, especially without it taking significantly longer to execute. I'll take a look, but I can't make any promises.

**Comment by dkaszews** [comment]
I would be happy to work on a minimised version which only supports grouping and sorting, as that is my (and likely many others') main concern.

**Comment by LesFerch** [comment]
My current plan: Make a Reg.exe replacement in C#. It's a more interesting project than revisiting the PowerShell code and less likely to introduce errors. I'll check for the `DisableRegistryTools` registry setting and only use my replacement tool when Reg.exe is blocked. I've already got Import and Export working. Working on Query, Add, and Delete...

**Comment by dkaszews** [comment]
Sounds amazing, a bit funny that you find it easier to replace the tool rather than calls to it 😄

**Comment by LesFerch** [comment]
Please test the attached update. It contains one file to add to the AppParts folder (CSReg.exe) and a replacement WinSetView.ps1 file.
[WinSetView.zip](https://github.com/user-attachments/files/17454804/WinSetView.zip)

**Comment by dkaszews** [comment]
Hi, I copied the files and invoked it as `./WinSetView.ps1 Defaults/Win10-Microsoft-Defaults-No-Groups.ini`, there are some errors:

```
Error exporting registry: Unsupported root key: "HKCU
Error deleting registry key or value: Unsupported root key: "HKCU
The property 'logo' cannot be found on this object
The variable '$C2' cannot be retrieved because it has not been set. 
File not found: Temp\ShellBak.reg
```

The first two look to me like quoting issue.

Overall, the script did not work, subdirectories still grouped and sorted by date.

**Comment by LesFerch** [comment]
That's weird. It works fine for me for both Administrator and Standard users. I even executed the exact same command that's in your reply. Maybe it's a regional issue with quote handling. What region setting are you using?

**Comment by dkaszews** [comment]
Locale is EN-GB, if that's what you mean. Running under PS 7.4.0

**Comment by dkaszews** [comment]
Is there a branch where I could see the source code of the exe to try and figure out what went wrong?

**Comment by LesFerch** [comment]
En-GB is not an issue. It's probably PS 7.x. Try it under PS 5.1. I'll test under PS 7.x...

**Comment by LesFerch** [comment]
PS 7.x is the issue. It will run fine under PS 5.1. I'll see if I can get it working correctly under PS 7.x. It's probably just a matter of removing extraneous quotes. PS 5.1 automatically removes extra quotes. PS 7.x does not.

**Comment by dkaszews** [comment]
Okay, I will check PS5.1 tomorrow and let you know

**Comment by LesFerch** [comment]
Thanks. CSReg.exe is fine. I have to make the changes to WinSetView.ps1. I will post the source to CSReg.exe when I update the repository.

**Comment by LesFerch** [comment]
Here are updated files to test. It was mostly a matter of getting rid of unnecessary quotes from the PowerShell script, but I also had to make one small change to CSReg.exe (needed to output a blank line after querying a value to match Reg.exe's output). I tested this with PowerShell 7.4.5 and the DisableRegistryTools policy value set to 2.
[WinSetView.zip](https://github.com/user-attachments/files/17470294/WinSetView.zip)

**Comment by dkaszews** [comment]
The new version almost works, there is still a warning about missing logo property, you should be able to fix it by replacing `).logo` with `% logo)`.

More important is that there is an error about unset `$C2`, I can see it is only set conditionally for Windows builds 19045..21995, while I am on 22631. No clue what should be the default value.

Result of running the script is that grouping is removed recursively (amazing!), but sorting stays on date.

**Comment by dkaszews** [comment]
I defaulted all `$CX` to empty strings and changed `).logo` to `| % logo -ErrorAction SilentyContinue)`, script completes without errors. The sorting was fixed by editing the config, replaced the `SortBy=-DateModified` line with `SortBy=+ItemNameDisplay`.

Everything is as I wanted now, thank you so much!

**Comment by LesFerch** [comment]
No manually editing should be required, so I'll keep at it until it's right. No errors for me, so it might take a bit of trial and error. Busy day today. Hope to get back at it tomorrow.

**Comment by dkaszews** [comment]
Errors might be caused by my environment running under `Set-StrictMode -Version 3`, which mostly generates warnings about accessing non-existent variables or properties. It's a good idea to put it on top of all your scripts as it helps catch bugs, anything you find spurious can be explicitly silenced one way or another.

The config edit is not needed if using the Web UI to generate your own, it was just easier for me to do all from console to focus testing on the modified scripts.

**Comment by LesFerch** [comment]
Version 2.99.1 now includes the updates to work on systems where the DisableRegistryTools policy has been set.
