### ISSUE TITLE
Minor typo in example file

### ISSUE THREAD

**Issue by SumatraPeter** [LesFerch/WinSetView#13]
(I didn't see a way to simply leave a comment on the file itself, hence this issue that can be quickly resolved and closed.)

https://github.com/LesFerch/WinSetView/blob/c14a4bbaef2402820950df066e631c33084f9b02/AppData/WinSetViewCustom.txt#L11

Minor typo, should say "first". Also, the following comment can perhaps be added right below this one:

> ; See https://docs.microsoft.com/windows/win32/properties/props for a complete list of Windows Properties

**Comment by LesFerch** [comment]
Thanks. fist already corrected to first. :)

I wonder if there's a better reference out there. Unless I
missed something, that link doesn't seem to help much with the FolderTypes
registry key format. Everything I've learned about that key has been from a
combination of trial and error and reading posts by Keith Miller (mainly on
TenFormus.com).

**Comment by SumatraPeter** [comment]
Not the FolderTypes reg key format but as mentioned a complete list of all supported properties (for columns) like "prop:System.ItemType;System.ItemNameDisplay" etc.
