### ISSUE TITLE
WinSetView "opening" but won't "open."

### ISSUE THREAD

**Issue by discgolfdc** [LesFerch/WinSetView#136]
Hi.

I'm pretty sure my computer (a 13" notebook shipped with Windows 11) was previously able to run WinSetView successfully, but it has since updated to Windows 11 24H2 -- I don't know if that's the issue here.

When I start WinSetView (either installed version or portable), I get an instance on my taskbar, but clicking on it won't open into a full program window. In fact, clicking on it seems to do nothing at all. Hovering over it shows an empty white preview with the title of what should be the program window, but it just won't open. Not sure if I'm doing something wrong or what. Haven't made any changes to my system that I think would otherwise interfere with the running of this program.

Video: https://github.com/user-attachments/assets/74e407d2-33ba-4aac-a77b-7b8fb3ef2897

From about the 6-second mark to about 12 seconds, I'm just feverishly clicking on the taskbar instance of WinSetView to no avail.

Any insight here?

Thanks.

**Comment by LesFerch** [comment]
I've seen this occasionally. Usually it loads after about 5 seconds and then is fine after that. I put it down to some OS initialization of certain components and/or Windows Defender scanning stuff. A couple of times I saw a 30 second delay. My suggestion is leave it for a bit, try restarting, and do a check for Windows updates (sometimes just running Windows Update fixes mysterious behavior like this). If no luck today, leave it and try again tomorrow.

**Comment by discgolfdc** [comment]
I'd left it open for well over 20 minutes with no change in status. The
computer is up to date with Windows Update.

I'll restart and see if anything changes there. If not, I'll leave it on
overnight and try all again. If nothing works, I'll reach back out. I've
never otherwise seen it do this.

**Comment by LesFerch** [comment]
OK. One other thing to try is the beta JScript version, although if VBScript were blocked or disabled, you should see an error message. But it couldn't hurt to try. It's available [here](https://github.com/LesFerch/WinSetView/releases/tag/3.0.1).

**Comment by discgolfdc** [comment]
I wound up having to run it on my Windows 10 laptop from a USB stick,
letting it save my desired configuration in the Win10.ini file in AppData,
manually putting the Win10 filename into the ps1 file back on my Windows 11
machine, and executing the ps1 file there manually.

I don't know why it won't open on my Win11 machine for the life of me. I
did restart and all and wait for it to figure itself out (probably about
half an hour to no avail). I did run it as Administrator, too.

Dunno. Maybe something to look into further if you get this feedback from
others. Could it be a one-off thing? Maybe.

I'll see if it opens the JS beta version.

**Comment by discgolfdc** [comment]
The same Win11 machine has a similar problem with the JS beta version.
Opens in the Taskbar, but can't actually ooen it into a full window. Just
sits in the taskbar. Can hover over it to close it with the red X, but
that's about it. 🤷

**Comment by LesFerch** [comment]
That may indicate something amiss with MSHTML. Let's see how it is tomorrow or maybe wait until the next Windows or Defender update. You could also try a repair via Windows update. That's really easy to do now with 24H2. Details here:

https://www.elevenforum.com/t/repair-install-windows-11-with-an-in-place-upgrade.418/#One

**Comment by discgolfdc** [comment]
Well, it literally just did the upgrade to Win11 24H2 just a couple of days
ago, so my suspicion that it would need another in-place upgrade/reinstall
is low. I guess I'll try again after another update or two, but for now,
I've achieved my end with a workaround. I know the workaround isn't ideal
as pertains to where it leaves this issue. I'll be interested to see if
others have similar experiences.

**Comment by LesFerch** [comment]
Since I can't replicate the behavior, and there are no other reports, it would seem to be either something corrupted in Windows (possibly in the registry) or some AV software blocking it (unlikely if you only have Windows Defender).

I think it's worth trying a repair via Windows Update. That leaves all apps and data in place, so it's pretty easy.

I'm closing this for now, but you can still reply.

**Comment by LesFerch** [comment]
@discgolfdc Delays on opening seem to have been a result of WinSetView checking for a newer version on startup. Depending on network security settings, VPN in use or not, and possibly if Windows just had an update, there could be a timeout (not in my control) of various length. I've changed the code so there is no longer a check at startup. Instead, there's a button to manually initiate a check. This change is currently only in the beta (WinSetViewJScriptBeta.zip), that you can find [here](https://github.com/LesFerch/WinSetView/releases).

**Comment by discgolfdc** [comment]
Appreciate your reaching back out. I will test that on the affected
computer and report back.

**Comment by discgolfdc** [comment]
I was able to test the 3.1.3 release and pressing F5 seems to have brought
up the application window. Interesting, as I don't have a second display
attached for it to attempt to open on a second display.

**Comment by LesFerch** [comment]
Yes, interesting. I don't have an explanation, but good to hear that's all it was.
