### ISSUE TITLE
Additional Customization

### ISSUE THREAD

**Issue by WasabiWarlord75** [LesFerch/WinSetView#14]
You're doing some amazing work helping us customize the flow of file explorer, would it be possible to implement the following additional features?
- Edit the column width of the 'Small Icons' view
- The ability to set the default zoom size of icon views (I like to view images on a certain size between the the large and medium icon views)

**Comment by LesFerch** [comment]
@WasabiWarlord75 I could not find any way to adjust the column width for small icon view or list view. If you know of any way, please let me know. The icon size, however, is adjustable in Explorer (Ctrl-mouse-wheel) and corresponds to the IconSize registry value. I'll add an interface element to allow setting a custom icon size.

**Comment by WasabiWarlord75** [comment]
Much appreciated!

**Comment by LesFerch** [comment]
WinSetView v2 is now posted. It includes the requested Icon Size setting.
