### ISSUE TITLE
Error saving changes in WinSetView

### ISSUE THREAD

**Issue by explor202** [LesFerch/WinSetView#140]
I just installed WinSetView on a different PC running W11 22H2, build 22621.4391. When I click "Submit", I see the following error message, and many of the Explorer folder view options are not set and saved. Any idea on how to resolve the error and get the settings to save?

`Get-CimInstance : The specified service does not exist as an installed service.
At C:\Users\User\Downloads\WinSetView\WinSetView.ps1:176 char:15
+ ... $userSID = (Get-CimInstance -ClassName Win32_UserAccount -Filter "Nam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070424,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand`

**Comment by LesFerch** [comment]
Normally that service would be installed and enabled. Is this a work computer that is centrally managed?

If not, you could do a repair following the steps at the link below. It will keep your apps and data. Otherwise, I'll look into solutions/workarounds later today when I have a spare moment.

https://www.elevenforum.com/t/repair-install-windows-11-with-an-in-place-upgrade.418/#Two

**Comment by explor202** [comment]
> Normally that service would be installed and enabled. Is this a work computer that is centrally managed?
> 
> If not, you could do a repair following the steps at the link below. It will keep your apps and data. Otherwise, I'll look into solutions/workarounds later today when I have a spare moment.
> 
> https://www.elevenforum.com/t/repair-install-windows-11-with-an-in-place-upgrade.418/#Two

This is a personal PC that I very recently installed W11 on (12/03/2024) using a new SSD and the same USB stick that I used on 7 other PC's (2 of which successfully run WinSetView); I'm not sure a repair of the install will do anything.

**Comment by explor202** [comment]
FYI I'm able to get WinSetView to work as expected in Safe Mode.

**Comment by LesFerch** [comment]
That suggests something like anti-malware software is blocking or interfering.

**Comment by explor202** [comment]
Yup, sorry for have wasted your time. I used Comodo firewall and didn't realize I had forgotten to change it's default "Auto-Containment" setting to "Disabled". I have done that now though and WinSetView working as expected.

**Comment by explor202** [comment]
Closing this.

**Comment by LesFerch** [comment]
> Yup, sorry for have wasted your time. I used Comodo firewall and didn't realize I had forgotten to change it's default "Auto-Containment" setting to "Disabled". I have done that now though and WinSetView working as expected.

No problem. Great to hear you got it sorted. I'll look into possibly handling that error in some way.
