### ISSUE TITLE
Powershell script options?

### ISSUE THREAD

**Issue by aasimenator** [LesFerch/WinSetView#15]
Hi,

First off this is one amazing script, It worked better than expected vs the "Backup and Restore Folder View Settings" I was using previously where it would randomly set the contents inside a folder into groups or different views than what I had set it to.

I need your help with running this as a command-line option rather than the UI because I would like to run it on all our PC's during the log-on process. 

This is what I am currently running on 1 PC that I use, I would like to apply this on all pc's either via command-line by specifying options to your "WinSetView.ps1" file or some other way.
![image](https://user-images.githubusercontent.com/49643079/123633102-65a3cf80-d836-11eb-820f-18460ba1d3c2.png)

**Comment by LesFerch** [comment]
You should see that a file named "WinSetViewParams.txt" has been created in
the script's AppData folder. Also in that folder you will find
"WinSetView.vbs".

Run:

*WinSetView.vbs  WinSetViewParams.tx*t

Please try it and let me know if that works for you.

Another option is to use either the Cmd or Powershell version of the
Explorer views backup and restore scripts I posted on TenForums (and modify
them to take a file name as a command line parameter). Unlike the
"official" script on that thread, my versions also capture and restore the
FolderTypes key, making it perfect for capturing and restoring the results
of WinSetView. I haven't measured the performance of the two approaches,
but logically, the simple restore should execute faster.

See the following thread and go to page 7 to find my posts with the Cmd and
Powershell scripts:

https://www.tenforums.com/tutorials/17777-backup-restore-folder-view-settings-windows-10-a-7.html

When I get a chance, I'll modify those scripts to take a file name on the
command line and then post them to GitHub.

**Comment by LesFerch** [comment]
Actually, it makes no sense to modify those scripts. The restore is just a
one liner. So, the cleanest way is to use WinSetView to set up the options
you  like, use Explorer to set any further options, such as specific
settings for Pictures, Videos, Control Panel etc, and then run the backup
script to capture everything to a reg file. Import the reg file for any new
user profile. In most situations, you would not want to apply it on every
login.

The one liner is simply:  *Reg Import RegFileName.reg*

**Comment by LesFerch** [comment]
In most cases, you won't even need the separate backup script.
WinSetView creates a backup reg file on every run, so you can use that
unless you want to capture a few more things that the backup
script captures, such as the Control Panel view.

**Comment by LesFerch** [comment]
See the WinSetView v2 readme. There are several options for applying your preferred settings via command line.
