### ISSUE TITLE
Startup Error: "Format of the file <WinSetView.hta" could not be determined"

### ISSUE THREAD

**Issue by tobwz** [LesFerch/WinSetView#20]
When starting (double clicking) WinSetView.hta I got always an error popup:

"Format of the file <WinSetView.hta" could not be determined"

![startup error WinSetView](https://user-images.githubusercontent.com/60912225/131245480-753761c7-14ef-4afe-a2b0-e11dfc9c7bf6.png)

Whats wrong?

How can I repair this?

This worked in the past.

**Comment by LesFerch** [comment]
Do you have xnview installed? That's the only reference I found to that error:

https://forum.xnview.com/viewtopic.php?t=28989

Check the file association. Right-click WinSetView.hta and select **Open with** and **Choose default program**. On Windows 7, it should look like this:

![image](https://user-images.githubusercontent.com/79026235/131252663-90bf7e29-a283-46c3-b16f-da04ea174470.png)

**Comment by tobwz** [comment]
You are right. Curious.
