### ISSUE TITLE
Open dialog, icons are too large.

### ISSUE THREAD

**Issue by abactuon** [LesFerch/WinSetView#21]
![q](https://user-images.githubusercontent.com/90440695/132808079-08cc9c0e-a605-49e8-8658-14d89de88f9e.jpg)

![q1](https://user-images.githubusercontent.com/90440695/132808780-d465323d-e1ba-4ec4-b5ea-82006e86ff0e.png)

IconSize>48

**Comment by LesFerch** [comment]
Thanks for catching that! I was missing a decimal to hex conversion step in the PowerShell script that only affects icon size in open/save dialogs. It's now fixed in the Main branch. Please download and test again.
