### ISSUE TITLE
WinSetView.hta opens as blank window

### ISSUE THREAD

**Issue by tobwz** [LesFerch/WinSetView#22]
When I double click on the WinSetView.hta file on a certain (64bit Win7) 
computer then only a blank page opens (see attached snapshot).

Even when I wait 10 minutes or reboot the whole computer it does not help.

On other (Win7) computers the same file works.

Whats wrong?

![problem blank window after  hta start](https://user-images.githubusercontent.com/60912225/132983884-907cc048-6206-40dc-b7de-d2e76ed1830a.png)

**Comment by LesFerch** [comment]
@tobwz I could not yet recreate this issue on Windows 7 (tested on both virtual and physical machines). What type of drive is D: in the screenshot? USB flash drive? Network drive? What antivirus or antimalware software is installed?

**Comment by LesFerch** [comment]
@tobwz On a machine that has the issue, please right-click **C:\Windows\System32\mshtml.dll** and then select **Properties**. You should see something like this:
![image](https://user-images.githubusercontent.com/79026235/133263003-188035a1-8d05-44a0-9167-55c20ad93084.png)

**Comment by tobwz** [comment]
@LesFerch:

D: is a partition on hard disk.
No antivirus is installed.
"Details" tab shows exactly what your snapshot shows.

Curiously it worked in the past on the same computer.

I must have changed accidentally something on that machine which prevents correct execution of *.hta files.

Eventlog shows no error. Really strange

**Comment by LesFerch** [comment]
Yes, very strange. It shouldn't make a difference, but please try running it from drive C:

**Comment by tobwz** [comment]
This has nothing to do with Aero Theme with transparency. On other Win7 computers with Aero it works.

I guess its because the Visual Basic Runtime or association or registry setup is somehow accidentally damaged.
Which VB runtime version is at least necessary?
Maybe I have to reinstall it

**Comment by LesFerch** [comment]
Yes, I finally got a Windows 7 machine built with Aero and transparency and WinSetView was fine.

VB Runtime is not applicable. WinSetView is an HTA with VBScript code, so it uses MSHTA.exe, MSHTML.dll, and VBScript.dll.

The only thing I can think of trying is to uninstall/reinstall Internet Explorer 11. Although HTAs do not need IE installed, they share the same browser engine, so reinstalling IE could possibly repair what's broken.

Steps:
Control Panel
Programs and Features
Turn Windows features on or off
Uncheck Internet Explorer 11 and then click Yes and then OK
Repeat above steps, doing check instead of uncheck

**Comment by LesFerch** [comment]
@tobwz Have you tried the IE 11 remove/install steps from my previous comment?

**Comment by tobwz** [comment]
@LesFerch:
I doubt that this is an IExplorer error.
I never touched Internet Explorer since years.
I always use Firefox/Chrome.
I am still seaching for a way to repair the HTA.
I guess its an Registry error.
I think its not a bug in WinSetView but in my Win7 system.
Currently I have not much time due to other work.
So leave this issue open.
I will revert as soon as I resume investigations.
Thank you

**Comment by LesFerch** [comment]
@tobwz It doesn't matter which browser you use. HTAs use the Internet Explorer browser engine (MSHTML.dll). If there is an issue with MSHTML.dll, removing and reinstalling Internet Explorer could fix the issue. It's a simple and quick thing to try.

**Comment by LesFerch** [comment]
@tobwz Did you try my suggestion?

**Comment by LesFerch** [comment]
Closed due to inactivity.
