### ISSUE TITLE
Ansicht wird nicht übernommen

### ISSUE THREAD

**Issue by Conan179** [LesFerch/WinSetView#25]
Hallo erst mal.
Ich hab da ein kleines problem, ich hab bei Bildern und Videos eine andere Einstellung wie bei Global gesetzt, bei mir wird die Einstellung nicht übernommen, sondern es immer das was bei "Allgemeine Elemente" eingestellt ist.
![winset_110322a2](https://user-images.githubusercontent.com/1906242/157883110-a52bb3c8-b16d-4480-a2e8-ce4464da3a9e.JPG)
![winset_110322b](https://user-images.githubusercontent.com/1906242/157881451-26641754-fdb2-4900-9a21-13990eab852d.JPG)
![winset_110322c](https://user-images.githubusercontent.com/1906242/157881517-9b18e49a-2a45-4360-b4d7-753355038e1d.JPG)
Andere einstellungen wie z.b. "erstell datum" anzeigen klappt ohne probleme.
Windows 10 Version 21H2 Build (19044.1586)

**Comment by LesFerch** [comment]
I just tested, with the settings that you've shown, and my Pictures and Videos folders were all displayed with extra large icons. 

I can replicate the behavior described by enabling the **Advanced** interface and checking the option **Make all folders generic**. With that setting checked, Videos and Pictures will have the same view as General Items, as expected. You could also get the same results with the **Keep Apply to Folders views** option checked, depending on what views you previously saved with File Explorer. Both of those options are _unchecked_ by default.

Please post a copy of your **Win10.ini** file from the **AppData** folder, so I can investigate further.

**Comment by Conan179** [comment]
Ok, hier ist der inhalt der win10.ini:

> [Options]
Language=de-DE
Font1=Segoe UI
Font2=Consolas
Size1=11
Size2=10
Scroll=1
Interface=1
Reset=0
ShowExt=1
CompView=0
Generic=0
SearchOnly=1
SetVirtualFolders=1
KeepViews=0
FileDialogOption=1
FileDialogView=7
FileDialogNG=1
ThisPCoption=0
ThisPCView=3
ThisPCNG=0
NetworkOption=1
NetworkView=2
NetworkNG=1
[Global]
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Downloads]
GUID={885A186E-A440-4ADA-812B-DB871B942259}
Include=1
Inherit=0
View=1
IconSize=
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,DateCreated;0,,Size
GroupBy=
SortBy=-DateCreated
[Generic]
GUID={5C4F28B5-F869-4E84-8E60-F11DB97C5CC7}
Include=1
Inherit=0
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated
GroupBy=
SortBy=+ItemNameDisplay
[Generic.Library]
GUID={5F4EAB9A-6833-4F61-899D-31CF46979D49}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated
GroupBy=
SortBy=+ItemNameDisplay
[StorageProviderGeneric]
GUID={4F01EBC5-2385-41F2-A28E-2C5C91FB56E0}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated
GroupBy=
SortBy=+ItemNameDisplay
[Generic.SearchResults]
GUID={7FDE1A1E-8B31-49A5-93B8-6BE14CFA4943}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated
GroupBy=
SortBy=+ItemNameDisplay
[Documents]
GUID={7D49D726-3C21-4F05-99AA-FDC2C9474656}
Include=1
Inherit=0
View=1
IconSize=
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=-ItemNameDisplay
[Documents.Library]
GUID={FBB3477E-C9E4-4B3B-A2BA-D3F5D3CD46F9}
Include=1
Inherit=1
View=1
IconSize=
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=-ItemNameDisplay
[StorageProviderDocuments]
GUID={DD61BD66-70E8-48DD-9655-65C5E1AAC2D1}
Include=1
Inherit=1
View=1
IconSize=
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=-ItemNameDisplay
[Documents.SearchResults]
GUID={36011842-DCCC-40FE-AA3D-6177EA401788}
Include=1
Inherit=1
View=1
IconSize=
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=-ItemNameDisplay
[Music]
GUID={94D6DDCC-4A68-4175-A374-BD584A510B78}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Music.Library]
GUID={3F2A72A7-99FA-4DDB-A5A8-C604EDF61D6B}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[StorageProviderMusic]
GUID={672ECD7E-AF04-4399-875C-0290845B6247}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Music.SearchResults]
GUID={71689AC1-CC88-45D0-8A22-2943C3E7DFB3}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Pictures]
GUID={B3690E58-E961-423B-B687-386EBFD83239}
Include=1
Inherit=0
View=8
IconSize=256
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,Image.HorizontalSize;0,,Image.VerticalSize;0,,DateCreated
GroupBy=
SortBy=+ItemNameDisplay
[Pictures.Library]
GUID={0B2BAAEB-0042-4DCA-AA4D-3EE8648D03E5}
Include=1
Inherit=1
View=8
IconSize=256
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,Image.HorizontalSize;0,,Image.VerticalSize;0,,DateCreated
GroupBy=
SortBy=+ItemNameDisplay
[StorageProviderPictures]
GUID={71D642A9-F2B1-42CD-AD92-EB9300C7CC0A}
Include=1
Inherit=1
View=8
IconSize=256
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,Image.HorizontalSize;0,,Image.VerticalSize;0,,DateCreated
GroupBy=
SortBy=+ItemNameDisplay
[Pictures.SearchResults]
GUID={4DCAFE13-E6A7-4C28-BE02-CA8C2126280D}
Include=1
Inherit=1
View=8
IconSize=256
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,Image.HorizontalSize;0,,Image.VerticalSize;0,,DateCreated
GroupBy=
SortBy=+ItemNameDisplay
[Videos]
GUID={5FA96407-7E77-483C-AC93-691D05850DE8}
Include=1
Inherit=0
View=8
IconSize=256
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Videos.Library]
GUID={631958A6-AD0F-4035-A745-28AC066DC6ED}
Include=1
Inherit=1
View=8
IconSize=256
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[StorageProviderVideos]
GUID={51294DA1-D7B1-485B-9E9A-17CFFE33E187}
Include=1
Inherit=1
View=8
IconSize=256
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Videos.SearchResults]
GUID={EA25FBD7-3BF7-409E-B97F-3352240903F4}
Include=1
Inherit=1
View=8
IconSize=256
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Contacts]
GUID={DE2B70EC-9BF7-4A93-BD3D-243F7881D492}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Contacts.Library]
GUID={524DDB2B-2A4F-43B8-B8FE-E91EF9D8BA69}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Contacts.SearchResults]
GUID={20338B7B-531C-4AAD-8011-F5B3DB2123EC}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[HomeFolder]
GUID={24CCB8A6-C45A-477D-B940-3382B9225668}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[UserFiles]
GUID={CD0FC69B-71E2-46E5-9690-5BCD9F57AAB3}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[UserFiles.SearchResults]
GUID={E053A11A-DCED-4515-8C4E-D51BA917517B}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay
[Searches]
GUID={0B0BA2E3-405F-415E-A6EE-CAD625207853}
Include=1
Inherit=1
View=7
IconSize=96
ColumnList=0,34,ItemNameDisplay;0,34,ItemFolderPathDisplay;0,,DateModified;0,,ItemTypeText;0,,Size;0,,DateCreated;1,,ItemType
GroupBy=
SortBy=+ItemNameDisplay

**Comment by LesFerch** [comment]
Using your INI file, everything is correct on my computer. The Pictures and Videos folders are displayed with extra large icons.

Let's check your folder types. For the folders that are _not_ set correctly, please do this:

1. Open the folder
2. Right-click in the white space and select `Customize this folder...`
3. What is shown under `Optimize this folder for`? Does it show `Pictures` or `Videos` or does it show `General items`?

Also, is your computer your own person machine or is it a company-owned computer? I ask because, if it's the latter, it's possible for the company to control many of the settings via GPOs.

**Comment by Conan179** [comment]
Beim Bilder Ordner "Bilder" im Filme Ordner "Filme" so wie es seihen sollte.
Privater PC, nur ich hab zugriff.

**Comment by LesFerch** [comment]
It doesn't makes sense. Pictures and Videos should be displayed with extra large icons. I would like to know if a different user on the same computer gets the same results. Can you create another users account, login as that user, run WinSetView with the same settings and see if it works correctly? It may also be helpful to try WinSetView on another computer (or a virtual machine) at your location and see if the results differ.

**Comment by LesFerch** [comment]
Cannot recreate issue. No further communication from issuer.
