### ISSUE TITLE
HTA is not opening on Windows 11 Preview

### ISSUE THREAD

**Issue by randyrants** [LesFerch/WinSetView#26]
Hi,

Feel sheepish for posting this but all of my troubleshooting hasn't yielded results but:
- When I unzip and run the package on the released version of Windows 11 (22000.556) the HTA opens fine
- When I do the exact same on a Preview of Windows 11, the HTA does not open - no error messages but nothing happens.

Don't know if there's a version check somewhere in the mix or something in the Registry has changed location but wanted to send in a heads up, if a change is needed on a future build.

Thanks!

**Comment by randyrants** [comment]
Preview is a release after 22000.556, part of the Windows Insider program.

No third-party anti-virus or anti-malware; just the build into Windows bits.

I do not see the application host in Task Manager; I do not see MSHTA,exe in the details tab.  Where reports that it's on the device in System32, so it's there.

.hta files are associated with Microsoft (R) HTML Application Host.

Event Viewer shows nothing of interest in Application or System logs.

**Comment by LesFerch** [comment]
Strange. So, presumably, MSHTA.exe loads momentarily and then exits without any message. Check registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options` it should contain an `mshta.exe` key with one entry for `MitigationOptions` set to `0x00000100 (256). If that's all in order, try the `ftype` and `assoc` commands detailed [here](https://superuser.com/questions/1322203/trying-to-run-an-hta-gives-this-app-cant-run-on-your-pc).

**Comment by randyrants** [comment]
Yep:
![image](https://user-images.githubusercontent.com/18704482/158858382-c6314b20-0cbd-431d-8104-8e6e3e4f7306.png)

I've had no luck with ftype and assoc on Windows 11 (in trying to set up other EXT associations) but ran it anyway - also confirmed it was set up in the UI.

No change in behavior.  Again, I just wanted to post this as aheads up that there may be a bump in the road coming.  I'll keep trying it with each new build that gets flighted.

**Comment by LesFerch** [comment]
Just to eliminate a user profile issue, can you create another account on that machine and try running WinSetView after logging in with that new account?

**Comment by LesFerch** [comment]
Are you testing the Dev channel preview (currently 22579)? All the other previews listed non the [ISO download page](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso) are older (e.g. 22000.194).

**Comment by LesFerch** [comment]
I tested with the Windows 11 dev channel preview 22579 and saw no issue. The HTA opened and worked correctly.

**Comment by LesFerch** [comment]
Cannot recreate issue. No further communication from issuer.

**Comment by IOANNB4R** [comment]
@LesFerch I think I found the cause for this issue. It seems that HTA can only open if extracted/located on a hard drive. I was trying here to open it from a network drive and it didn't open (just briefly, then closes without any error or warning.)

**Comment by LesFerch** [comment]
@[IOANNB4R](https://github.com/IOANNB4R) There must be more going on to cause that issue. I designed the app to run from a network drive, whether it's a mapped drive letter or a UNC path. I just tested it again on a network drive and it ran fine. Maybe your anti-virus/anti-malware software is being more restrictive when run from a network drive. I get a warning when running from a network drive (strange warning because the drive is on my local network):
![image](https://user-images.githubusercontent.com/79026235/172975861-c4219158-8083-469f-93f3-b8415e7a10f9.png)
But clicking `Run` allows it to continue and run normally.

**Comment by LesFerch** [comment]
@[IOANNB4R](https://github.com/IOANNB4R)

Please try resetting the Internet Properties Security settings to the default values:

1. Open **Control Panel**
2. Open **Internet Options**
3. If not grayed out, click the button **Reset all zones to default level**
4. Click **OK**
5. Try to run WinSetView.hta

![image](https://user-images.githubusercontent.com/79026235/173737252-93dc2ceb-b3a1-4da0-9059-9a675ee1ce46.png)
