### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Skrell** [LesFerch/WinSetView#28]
First of all this is a great app and seems to work great!   One thing that I might suggest is adding the option to disable folder thumbnails via this registry setting:  
[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell]
"Logo"="d:\\somefile.jpg"

I regularly do this and every time I run your app it undoes this setting.   Just a suggestion!  Thanks!

**Comment by LesFerch** [comment]
Thanks! That sounds like a good suggestion. I'll take a look tonight and post back here with an update.

**Comment by LesFerch** [comment]
Working on it. In the meantime, you can create a file named `WinSetViewCustom.reg` in the WinSetView `AppData` folder with the contents:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell]
"Logo"="nothing.jpg"
```

**Comment by LesFerch** [comment]
Done:
![image](https://user-images.githubusercontent.com/79026235/162346676-013558f0-db36-4953-8722-4fcaea4a08a6.png)

**Comment by Skrell** [comment]
Beautiful!!
