### ISSUE TITLE
Cannot install WinSetView

### ISSUE THREAD

**Issue by gmax51** [LesFerch/WinSetView#29]
Hello LesFerch ... I am not able to install this tool on win 11 ... also not sure I'm doing the install correctly. 1st)  I ran the powershell file, then 2nd) I opened the .hta file with internet explorer (or Edge ... not recalling which) ... 3rd) nothing hapens ... I'm not seeing this use case in your documentation.

**Comment by LesFerch** [comment]
There is no "install". This is a portable app. Simply download, extract, and run the HTA. The PowerShell script is run automatically by the HTA. Just follow the [instructions](https://lesferch.github.io/WinSetView).

**Comment by gmax51** [comment]
Hi Les ... thank you for quick response ... I've read the instructions more than once, they're really very good, but looks like I've accidentally created an edge case ... I've checked the .hta default app ... it is Microsoft HTML Application Host ... I just rebooted and clicked the .hta file ... still nothing happens ... would you describe what I should see if it opens correctly?

**Comment by LesFerch** [comment]
You should see the interface as shown in the documentation. Your anti-virus/anti-malware software may be blocking or quarantining the HTA, but it should display a message if that's the case. The HTA is designed to run from any drive, including network drives, but you never know. What drive and folder are you trying to run it from? I suggest trying from something like C:\Test and see if that makes a difference. Do also reboot if you just reassociated HTAs to MSHTA. Also I've seen issues where NotePad++ was configured to open HTAs. In that case,, clearing those associations fixed it

**Comment by LesFerch** [comment]
If it still doesn't open, try running it with a different user account (create another local account. if you don't already have one set up).

**Comment by LesFerch** [comment]
Also, after double-clicking the HTA, does a copy of **Microsoft HTML Application Host** remain running (i.e. is it listed in Task Manager)?

**Comment by LesFerch** [comment]
Please try resetting the Internet Properties Security settings to the default values:

1. Open **Control Panel**
2. Open **Internet Options**
3. If not grayed out, click the button **Reset all zones to default level**
4. Click OK
5. Try to run **WinSetView.hta**

![image](https://user-images.githubusercontent.com/79026235/173736573-ecb5f0bc-697e-4e74-b666-58659de9e167.png)

**Comment by LesFerch** [comment]
@gmax51 What's the status?

**Comment by LesFerch** [comment]
Cannot recreate issue. No further communication from issuer.
