### ISSUE TITLE
Restore folders on "This PC"

### ISSUE THREAD

**Issue by VictorPLopes** [LesFerch/WinSetView#30]
Hello. I wanted to get rid of Window's file grouping, so I downloaded your program. It worked very well, something which I'd like to thank you for. The issue is that I applied the tweaks to "This PC" too, which I didn't want. Now, although I was able to restore the tiles view with groups, the folders group (Desktop, Documents, Downloads, Music, Pictures and Videos) are gone, I can only see my drives. Is there any way to completely restore it to how it was?

**Comment by LesFerch** [comment]
It should just be matter of unchecking This PC". That is...

Run WinSetView again, go to Options, *uncheck* **This PC**, go back to main screen, click **Submit**.

**Comment by VictorPLopes** [comment]
I already tried that, didn't work. I ended up using WinAero Tweaker, which "fixed" it, although the "Desktop" folder isn't being sorted alphabetically correctly (for some reason Windows thinks it's the last folder in alphabetical order).

**Comment by LesFerch** [comment]
I'll have to see if I can recreate what you see when I'm back at a PC. I'll reply back here later.

**Comment by LesFerch** [comment]
I can't recreate what you I think you're describing. Can you post a screenshot?

**Comment by VictorPLopes** [comment]
Unfortunately I can't, since I found a work around with WinAero Tweaker. It was just the "This PC" "folder" (I don't know what else to call it) but only with the drives group, without any of other folders.

**Comment by LesFerch** [comment]
If you run WinSetView again, at this point, I assume the folders remain? The following article (which you probably saw) shows the registry settings to hide those folders. Maybe that provides some clue how they got hidden on your PC. When I get a cht, I'll play around with those registry settings to try to learn more.

**Comment by LesFerch** [comment]
Did you use any of the **Advanced** settings? In particular, the **Keep 'Apply to Folders" Views**?

**Comment by VictorPLopes** [comment]
> If you run WinSetView again, at this point, I assume the folders remain? The following article (which you probably saw) shows the registry settings to hide those folders. Maybe that provides some clue how they got hidden on your PC. When I get a chance, I'll play around with those registry settings to try to learn more.
> 
> https://winaero.com/windows-11-remove-folders-from-this-pc/amp/

I believe the article I saw was an older one, but yes, it's worth checking out. I will try to reproduce the issue tomorrow, as I am not home right now. When I do, I will describe exactly what I'm doing, screenshot the issue and check the registries, before and after.

**Comment by VictorPLopes** [comment]
> Did you use any of the **Advanced** settings? In particular, the **Keep "Apply to Folders" Views**?

I think when I first used the program I used the default settings.

**Comment by LesFerch** [comment]
> I will try to reproduce the issue tomorrow, as I am not home right now. When I do, I will describe exactly what I'm doing, screenshot the issue and check the registries, before and after.

Very much appreciated, but I would be surprised if you can reproduce it. Although I could hide those folders using the registry settings documented at Winaero, I couldn't come up with a scenario where the folders would be visible and then become hidden after running WinSetView.

**Comment by VictorPLopes** [comment]
> > I will try to reproduce the issue tomorrow, as I am not home right now. When I do, I will describe exactly what I'm doing, screenshot the issue and check the registries, before and after.
> 
> Very much appreciated, but I would be surprised if you can reproduce it. Although I could hide those folders using the registry settings documented at Winaero, I couldn't come up with a scenario where the folders would be visible and then become hidden after running WinSetView.

Alright, here is before doing anything in WinSetView (also, the alphabetical order issue fixed itself):
![image](https://user-images.githubusercontent.com/77900343/180768120-a5efe245-b08c-46b2-a169-6303d33aa62d.png)
All of the keys are set to "Show":
![image](https://user-images.githubusercontent.com/77900343/180768475-df331dc0-4cde-4933-bf61-9c60672d610e.png)

I was gonna send an image of what happens when I submit the default settings of WindSetView but you are right, I can't reproduce it. Yesterday, just applying the default settings was enough for issue to occur, now it just changes to a proper list. I have no idea what happened when I first used it.

**Comment by VictorPLopes** [comment]
Ok, so, I decided to use your software on my Laptop, this time, these were the settings I used:
![image](https://user-images.githubusercontent.com/77900343/180880755-ece5fa62-79a4-42f7-bfc9-8cf942b46dc6.png)
![image](https://user-images.githubusercontent.com/77900343/180880778-2f5c4dfd-4d7e-4e27-b008-c7ab6d6afe65.png)
After submitting the settings, everything seemed normal, but upon rebooting the computer, the folders under This PC were gone. Keep in mind that the "This PC" section wasn't even touched by your program, but the issue repeated itself on a completely different machine:
![image](https://user-images.githubusercontent.com/77900343/180881017-99f319df-0ef4-41b8-b622-67d5ea998702.png)
And to my surprise, the "ThisPCPolicy" value was gone:
![image](https://user-images.githubusercontent.com/77900343/180881253-3c03ca0e-d96c-458c-9d4c-b8e64ce00694.png)
With all this said, I think there really is something going on, maybe you could give it a second look?

**Comment by VictorPLopes** [comment]
Not sure if it could be the culprit but there is a "HideIfEnable" value under the folders' NameSpace keys (Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\). I'll see if deleting them and rebooting the computer fixes my issue.
![image](https://user-images.githubusercontent.com/77900343/180883543-e1626f1e-10da-48bd-9ddf-0b573b5005cb.png)

**Comment by VictorPLopes** [comment]
Yep, that did it
![image](https://user-images.githubusercontent.com/77900343/180884343-1185bfa4-ef2c-4c8f-af44-df31b334fb47.png)
For some reason, this values are getting created when using your program, at least on my end.

**Comment by LesFerch** [comment]
Thanks! Lots of good info! I'll research those settings tonight.

WinSetView does not touch any registry settings in HKLM, so if a registry
setting appeared there, it was either File Explorer or a third party
utility that created it.

Is there any chance both computers are in the same domain with roaming
profiles enabled?

Is there anything else that might be in common that could affect File
Explorer, such as Winaero Teaker?

**Comment by VictorPLopes** [comment]
Hmm, weird. Thanks for your time though, I appreciate it. The computers are not in the same domain, which makes it even weirder. There is one thing that could be affecting it but I really doubt it's that. I am on Windows 11 22H2, so I followed this to unlock the hidden tabs feature in Explorer: https://www.windowslatest.com/2022/06/16/how-to-enable-tabs-in-file-explorer-on-windows-11-22h2/
I did it for both computers, and WinSetView was used at the same time.

**Comment by VictorPLopes** [comment]
Alright, while giving the article a second read, I noticed something. Their explorer looks like mine after the bug, without the folders:
![image](https://user-images.githubusercontent.com/77900343/180891607-e8bda777-64fc-48e2-9be6-7f04ef35a05c.png)
So yeah, I suppose it's really not WinSetView's fault, I am really sorry for wasting your time and I should've checked that. Once again, thanks for everything though, your software has been of huge help to me.

**Comment by LesFerch** [comment]
Oh, no problem. I appreciate learning something new. Thanks!

**Comment by VictorPLopes** [comment]
You're welcome, I'll be closing this for now, since it's not an issue with your program.
