### ISSUE TITLE
WinSetView.hta does not start after updating to Windows 10 21H2 to 22H2 Pro - workaround?

### ISSUE THREAD

**Issue by WusWus** [LesFerch/WinSetView#36]
Hello,

Windows 10 22H2 does not start the "WinSetView.hta" on my PC. In my case the message appears:
"This app cannot be run on the PC".
There are no problems with Windows 10 21H2.

**Workaround 1:**
Start the "Command Prompt" in admin mode and enter the following command:
--> "C:\Windows\system32\mshta.exe" "#PATH#\WinSetView.hta"  ( #PATH# = Path to the file )

Now the program starts correctly.

**Workaround 2:**
1.) Create a shortcut of the file "WinSetView.hta". 
2.) Right click on shortcut: "Properties"; tab: "Shortcut"
3.) At "Target" insert the following before the file path: C:\Windows\System32\mshta.exe
(example: C:\Windows\System32\mshta.exe "#PATH#\WinSetView.hta" )
4) click "OK
5.) Double click on the shortcut to start the program.

With both workarounds the changed settings are applied.

Remark: 
When trying to assign the *.hta to "mshta.exe" with "open with", I get the message "The selected program cannot be assigned to the file type. Select another program."

**Comment by WusWus** [comment]
No, I do not use BitDefender. I have also tried with Antivir disabled. Same problem. There is no indication of any blocking events in the scanner log.

**Comment by LesFerch** [comment]
Same error reported [here](https://www.elevenforum.com/t/this-app-cant-run-on-your-pc-error-when-trying-to-install-explorer-patcher.9582/page-2) with a completely different app. OP fixed issue by applying Microsoft update KB5018427.

**Comment by LesFerch** [comment]
Please try updating to the latest Windows 11.  See this [issue](
https://github.com/LesFerch/WinSetView/issues/32). Updating to  Windows 11 22H2 Build 22621.674 did the trick.
