### ISSUE TITLE
3 digits for the column width.

### ISSUE THREAD

**Issue by ebmoluoc** [LesFerch/WinSetView#37]
1) It would be great if the column width had 3 digits or a limit above 99. A limit of 120 should be perfect to accommodate my 1440p monitor but someone with a 4k monitor could think my limit is still too low so 120 is totally arbitrary for my use case.

2) Thank you for this app. Windows seems to forget my settings occasionally and WinSetView will make it easy to set them back.

**Comment by LesFerch** [comment]
The column width is specified in **ems**. It's resolution independent (i.e. one em is approximately equal to one character). My thinking was that no one would want a column wider than 99 (or so) characters. You can specify the width in **pixels** by holding down Alt and then clicking in a width field (the value will be translated back to ems). Please double check, If you have a use case for columns greater than 99 ems, I can probably make the field allow three characters.

**Comment by ebmoluoc** [comment]
Setting the width in pixels doesn't bypass the ems limit and I have indeed my "name" column wider than 99 ems. Wider the resolution, the more text it fits.
That being said, if I'm the only one who have a need for that, I'll look at it later myself. Don't do that just for me.

**Comment by LesFerch** [comment]
Wow, you must have some very long file names. I also figured a width beyond
99 would be more of a temporary thing, versus a desired default. But one
should assume nothing. Anyhow, probably a very easy change. I'll take a
look.

**Comment by ebmoluoc** [comment]
The only case I have very long file name is for my music files which were named automatically with year, album, track and title. It can be quite long.
Also, I never use 2 File Explorer window in split screen so I use the full width of my monitor and set the columns width accordingly.

"But one should assume nothing", yeah, there's always a weirdo around the corner doing its weird things. This time, I think I am that weirdo, lol.

**Comment by LesFerch** [comment]
[Version 2.4](https://lesferch.github.io/WinSetView) is now available. It allows 3 digits (max column width 999 ems).

BTW, those long music file names can be trouble on older devices and car audio systems. Any good music file tag editor should let you rename them all in one shot in, any format you like, using whichever tag data you want in the name. I use [Tag&Rename](https://www.softpointer.com/tr.htm), but I assume [MP3Tag](https://www.mp3tag.de/en/) and others can do the same.

**Comment by ebmoluoc** [comment]
I tested it and it works like a charm. Hopefully I won't be the only one having a use for it. Thank you.

**Comment by LesFerch** [comment]
You're welcome. 🙂
