### ISSUE TITLE
Can't restore to windows default explorer

### ISSUE THREAD

**Issue by likertuban** [LesFerch/WinSetView#38]
hey, I want to restore my setting to default file explorer including all folder on "this PC" which has been gone for good >.<
but it seem I can't do it, my file explorer keep retaining winsetview explorer which is look more like a webview/microsoft edge instead of file explorer with all those tab at the top, even "Reset Views to Windows Defaults" and submitting, my file explorer doesn't change back to the way how it used supposed to be.
I used windows 11 enterprise 22H2 with latest update and latest driver update
current file explorer :
![image](https://user-images.githubusercontent.com/24775011/197108665-42375eea-44ba-4b40-8067-392b2cb61902.png)

how it should look like :
![image](https://user-images.githubusercontent.com/24775011/197108789-ef49f0e4-12c6-46d4-830a-20029319871b.png)

**Comment by LesFerch** [comment]
Please update to the latest version and try again. This was fixed in version 2.42. The latest version is 2.44.

**Comment by likertuban** [comment]
hey, I've downloaded the latest one from the github release asset, it doesn't works, the file explorer doesn't revert back to how the windows is :(

**Comment by LesFerch** [comment]
I think I misunderstood what you were looking at. I thought you were referring to the default view for "This PC" which is normally Tiles grouped by Type. That one particular view wasn't getting set back to default previously, but does as of version 2.42.

However, it sounds like you're talking about how File Explorer looks in general on Windows 11. That's Microsoft's doing. They are making tweaks to File Explorer with almost every Windows 11 update. They've now add tabs and changed various items to icons. That's nothing to do with WinSetView.

**Comment by likertuban** [comment]
it turned out you are correct,
I was updating my windows this morning, so I didn't realize the changing until I run the tool, and when I compared my PC which hasn't received the update to explorer, I was in a panic, sigh....
I am ashamed now...
sorry for the trouble, and thanks for the assistance...
