### ISSUE TITLE
Wrong symbols..

### ISSUE THREAD

**Issue by Cris--** [LesFerch/WinSetView#39]
Hi,

first big **thanks** for this necessary script. It makes the windows life so easier!

So here my issue. In my case some symbols didn't work here:

![mshta_CVkwXKOfDm](https://user-images.githubusercontent.com/7994691/197141214-72e99772-13df-4f54-9ccc-75fc58e9205f.png)

Seems i must downgrade my Windows to v7 or v8.. ^^

W11 22H2 de-DE (Build 22621.754), Powershell 5 & 7

And a little feature request: Option to set the default window size of WinSetView and maybe if possible remember last windows position also..

**Comment by LesFerch** [comment]
Those are just [Unicode characters](https://unicode-table.com/en/sets/arrow-symbols/#up-down-arrows) that should work on all Windows versions. Here is a screenshot from one of my Windows 11 test machines:
![image](https://user-images.githubusercontent.com/79026235/197195175-da7de6c4-6115-4f22-beaa-f6227a907410.png)
![image](https://user-images.githubusercontent.com/79026235/197195233-004df041-d284-4218-8683-7972a4673808.png)

Can you test on another Windows 11 computer and see if the results differ?

I'll look into having it remember window position. That would be a nice feature.

**Comment by LesFerch** [comment]
Did you try WinSetView on another Windows 11 computer?
