### ISSUE TITLE
Win 11 - (Blue) Column Never Shows In Search Results

### ISSUE THREAD

**Issue by amiga-500** [LesFerch/WinSetView#44]
Unless i am misunderstanding the User Manual i am unable to ever get any blue column (eg, Folder Path, Path, Folder) to show in search results.  I am using "Detailed" view.

Other columns work just fine.  Its just the blue ones that never show.  I understand the blue columns only reveal themselves in search results but, maybe its a windows 11 thing, they just dont show at all.

Is there some special steps i must do because right now I have to manually navigate More columns and check mark to show it. 

Also, none of the blue columns show in the right-click context menu during search results too.  Only the non-blue columns show.

I am setting this blue column for Global and all others are inheriting.  So under e.g. "General Items Search results" I have it showing "Name | Size | Date Modified | Type | Folder Path"

**Comment by LesFerch** [comment]
I just checked this on Windows 11 and found that it's working fine, but Microsoft has changed the display name for property **ItemFolderPathDisplay** from **Folder path** to **File location**. When you do a search, your search results should have a **File location** column where you were expecting to see a "Folder path" column.

**Comment by amiga-500** [comment]
thx for the reply.  Sadly, it doesnt work for me in Search Resutls.  And right-click menu does not include any of the blue items.  No clue why not.  I just realized though, i am using an extension called StartAllBack to add fixes to Windows 11 to make it more productively usable.  I wonder if that might be interfering with this tools ability for search results.  That is the only thing i can think of.  Besides this Search Results issue, this WinSetView tool works really well.  

Anway, off to do more trial-and-error tests until i give up.

thx for the reply nonetheless.

**Comment by LesFerch** [comment]
I've never tested StartAllBack and wouldn't expect it to interfere with folder views, but it couldn't hurt to eliminate that variable. The best way to troubleshoot this issue would be to first try it on another computer (or virtual machine). Please let me know what you discover. I like to follow up completely on all issues.

**Comment by LesFerch** [comment]
Is the problem drive removable? If so, then it's a Windows 11 bug. Folder views do not apply consistently on removable drives in Windows 11. It's been a known issue for over a year, but Microsoft appears to be ignoring it.

**Comment by amiga-500** [comment]
Ok i am giving up.  It seems for some unknown reason WinSetView has issues setting the search results column for a specific drive.  Since there is no debug messages i have no clue why not.  I will just write a script to manually traverse and set each folder/sub-folder to the correct columns to fix this.

**Comment by amiga-500** [comment]
Thanks for the info.  The drive is not removable, unfortunately.  It's a HDD. And via a Powershell check, to confirm Windows wasn't mis-typing my drive, it indeed says it is "Fixed" not "Removable".  

I decided to just move on.  Never did resolve the issue but decided to just manually set each folder on the drive to include the missing path column by hand.  So all good. Its fine now even though it's a superficial workaround for that drive. But it is what it is.

Thanks for your help nonetheless.

**Comment by LesFerch** [comment]
Hey Kimberly, thanks for following up. That is indeed strange. I still suspect a Windows 11 bug. The only way to confirm would be to install Windows 10 on that machine (either in a VM or a separate partition) and see if it works as expected in Windows 10. That's a time consuming task, so I understand if you don't bother, but please let me know the results if you do. Thanks!
