### ISSUE TITLE
Unchecking "Make all folders Generic" doesn't do anything

### ISSUE THREAD

**Issue by JAK0723** [LesFerch/WinSetView#52]
System info: Windows 11 Pro, Version 22H2, OS build 22621.963, Windows Feature Experience Pack 1000.22638.1000.0

I tried out the "Make all folders Generic" option, but I changed my mind and wanted to switch back. I unchecked the "Make all folders Generic" option and clicked the "Submit". I then tried checking "Reset Views to Windows Defaults" and even using "Restore" with my oldest backup, but they didn't work either.

I then checked the manual and found the registry key that is set by the "Make all folders Generic" option, `HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell > "FolderType"` and deleted it. This had the immediate effect of restoring the behaviour of Windows Explorer before I had tried out the "Make all folders Generic" option.

I believe that unchecking the "Make all folders Generic" option should delete or render ineffective the aforementioned registry key. If this is already the intended behaviour, then it doesn't work on my machine and it requires manual editing of the registry to fix.

**Comment by LesFerch** [comment]
Oh, yikes. I see I introduced this bug with the latest update when I added the feature for the app to remember its window position. The same key that contains the window position information also contains that FolderType value. I have to add a line to clear that value before backing up that key. I'll get that fix done and posted shortly. Sorry I missed this in testing the latest version and thanks so much for reporting it.

**Comment by LesFerch** [comment]
I've now corrected this in the main branch files (the same files you get via the WinSetView web page download link). I didn't do a version number change since I'm releasing 2.54 (which includes a couple of new items in the Options menu) very soon.
