### ISSUE TITLE
Huorong detects hta file as potential malware

### ISSUE THREAD

**Issue by mo-han** [LesFerch/WinSetView#60]
hta is used by some malware to bypass antivirus, and some guardian softwares simply wipe this type of files

**Comment by LesFerch** [comment]
I have submitted a false positive report to [seclab@huorong.cn](mailto:seclab@huorong.cn).

**Comment by LesFerch** [comment]
Huorong has updated their definitions to correct the false positive. Please update your definitions. WinSetView should now scan clean.
