### ISSUE TITLE
WinSetView will not start on one computer

### ISSUE THREAD

**Issue by mxypltk** [LesFerch/WinSetView#61]
WinSetView starts fine on three of my computers:  two Win 11 Pro, one Win 10 pro.  However, on a fourth computer when I click winsetview.exe an icon appears on the taskbar and nothing else happens.  Right clicking the icon shows the following:
[WinSetView Taskbar Window.pdf](https://github.com/LesFerch/WinSetView/files/10960873/WinSetView.Taskbar.Window.pdf) 
with no other messages.  I also tried to start it using winsetview.hta with the same result.  

Any suggestions would be appreciated.

**Comment by LesFerch** [comment]
Probably loaded off screen. Try pressing any function (F1 - F12) after launching it. That should automatically re-center the app on the primary display.

**Comment by LesFerch** [comment]
Bump

**Comment by LesFerch** [comment]
No further response from OP.

**Comment by LesFerch** [comment]
This was happening when WinSetView was closed while minimized. Fixed in version 2.71.
