### ISSUE TITLE
Two disk units in my computer

### ISSUE THREAD

**Issue by neohazuki** [LesFerch/WinSetView#62]
After running the program, it generates two disk units.

https://prnt.sc/qyU1eio1addW

**Comment by LesFerch** [comment]
You can paste screenshots directly here on GitHub. No need for third-party links.

I think something else is going on. You can read in the manual how WinSetView works, but in summary, it sets a FolderTypes key in HKCU and clears Explorer's per-folder saved views by deleting the BagMRU/Bags key in HKCU. None of that would explain an additional disk showing up. Does the additional disk remain after a logout/login or a restart?

**Comment by neohazuki** [comment]
`You can paste screenshots directly here on GitHub. No need for third-party links.`
Lightshot create screenshot link auto.

`You can paste screenshots directly here on GitHub. No need for third-party links.`
yes, it remains yes, after restarting the machine and also after logoff.

**Comment by LesFerch** [comment]
Try it with these two options unchecked:
![image](https://user-images.githubusercontent.com/79026235/225374408-bc04f304-8101-4f25-834f-bfdd09f323d6.png)

**Comment by neohazuki** [comment]
`Try it with these two options unchecked:`
not work.

when i go back the windows registry this happens
![image](https://user-images.githubusercontent.com/1298112/225391470-7ea43207-30f5-40a1-856a-3b132be8f509.png)

**Comment by neohazuki** [comment]
i find solution. tnx for help

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\DelegateFolders` or `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\DelegateFolders`
delete `{F5FB2C77-0E2F-4A16-A381-3E560C68BC83}` and delete it.

**Comment by LesFerch** [comment]
Glad to hear you found a fix.
Those settings have nothing to do with WinSetView.
WinSetView does not touch any settings in HKLM. It only updates HKCU.
