### ISSUE TITLE
When i downloaded file from Your GithHub repository Defender detect virus:

### ISSUE THREAD

**Issue by MxLexmark** [LesFerch/WinSetView#65]
When i downloaded file from Your GithHub repository Defender detect virus:

![image](https://user-images.githubusercontent.com/129328996/228649503-b7ae7835-cf6e-4c02-be73-3a25fd26a39c.png)

Please, correct your file. Thanks.

_Originally posted by @MxLexmark in https://github.com/LesFerch/WinSetView/discussions/64_

**Comment by LesFerch** [comment]
Nothing to correct. It's a false positive. What browser are you using? I see Opera in the path.

**Comment by LesFerch** [comment]
I just double-checked. There are no issues with Windows Defender. Unless I hear otherwise, I have to conclude that you have very old definitions.

**Comment by LesFerch** [comment]
I have found that if Defender has previously detected the same "virus", it sometimes keeps detecting it even in files that have been cleared by the Windows Defender team (such as WinSetView). The solution in such cases, is to clear the Defender history files using the script available **[here](https://lesferch.github.io/ClearDefenderHistory/)**.
