### ISSUE TITLE
Settings for the folder Quick access

### ISSUE THREAD

**Issue by Marc550218** [LesFerch/WinSetView#71]
It seems that WinSetView settings in win10.ini are not taken into account by the powershell script WinSetView.ps1 to create the WinSetView2.reg.
Win.ini:
ColumnList=0,34,ItemNameDisplay;0,,ItemFolderPathDisplay
GroupBy=
WinSetView2.reg after execution of WinSetView.ps1:
"ColumnList"="prop:0(34)System.ItemNameDisplay"
"GroupBy"="System.Home.Grouping"

This results in an incorrect display of the columns and folders grouping in the explorer.exe
Column: Only name of the folders
Grouping: Most frequent folders

Manual intervention in the WinSetView2.reg with the correct settings gives the correct display in the explorer.exe:
"ColumnList"="prop:0(34)System.ItemNameDisplay;0System.ItemFolderPathDisplay"
"GroupBy"=""

**Comment by LesFerch** [comment]
Working as intended. As of version 2.72, grouping for Home/Quick Access is always set to "group". The latest version of File Explorer (available in Canary build) crashes if Home/Quick Access is not grouped. It's also kind of strange to not group that folder because then you'll have pinned items mixed with most recent items.

**Comment by LesFerch** [comment]
Your detailed use case convinces me that I should add an option. Ideally I should detect if the new File Explorer is in use, but I could find no way to do that, other than finding a redirected CLSID that is likely to change in the future. So, I think I'll add a check box in the Options menu (in Advanced mode) in the next update.

**Comment by LesFerch** [comment]
In the meantime, you can use version 2.73 by commenting out or removing the following lines (lines 434-437) in WinSetView.ps1:
```
      If ($FT -eq 'HomeFolder') {
        $GroupBy = 'Home.Grouping'
        $GroupByOrder = '+'
      }
```

**Comment by Marc550218** [comment]
Good workaround. I test it and it is ok. I think the new option in advanced mode is a good solution, so many people seeming to dislike the group by option of the explorer.exe. Thanks.

**Comment by LesFerch** [comment]
WinSetView 2.74 now includes the advanced mode option we discussed.
