### ISSUE TITLE
"Math.Min" function throws error on non-updated Windows 7

### ISSUE THREAD

**Issue by Getfree** [LesFerch/WinSetView#73]
I've just run this tool on a computer with IE8 (Windows 7). I never cared to update IE as I never use it.
When I click on one of the "Options", a script error dialog box shows up saying that "Math" is undefined:
https://github.com/LesFerch/WinSetView/blob/fccf61396d713585160801f2077a58a4326f5706/Src/WinSetView.htm#L978

The previous issue that I opened also happened on a Windows 7 machine but with IE11. There was no script error there.

**Comment by LesFerch** [comment]
Interesting. Although WinSetView does not depend on IE being installed, it does use MSHTML, which is the same rendering engine used by IE and is typically only updated when IE is updated. WinSetView uses MSHTML in IE 8 mode (to be as backward compatible as possible) so it's surprising that the Math function works with MSHTML 11 running in 8 mode when it's actually missing from the original MSHTML 8. At least it's easy enough to replace that call with a couple of variables and a simple comparison, so I'll do that.

**Comment by LesFerch** [comment]
I built a non-updated Windows 7 VM and found that there were several other issues running WinSetView via the old MSHTML 8. Therefore, I've included an MSHTML version check in WinSetView 2.74:

![image](https://github.com/LesFerch/WinSetView/assets/79026235/c038802b-e025-4350-8934-598a4d8c855a)
