### ISSUE TITLE
Breaks sorting somewhat

### ISSUE THREAD

**Issue by Polygon1177** [LesFerch/WinSetView#75]
When I use WinSetView, the Sort entries in my Windows 11 22H2 Home explorer ribbon are grayed out. I can still sort by right-clicking in the folder view and using the context menu though. And another thing: when I use WinSetView, Sort in the Windows explorer context menu doesn't show what type of sorting I am currently using. When I go back to Windows defaults in WinSetView, all this is fixed.

**Comment by LesFerch** [comment]
I've never seen what you describe. Please post screenshots and email me a copy of your win10.ini file. Thanks.

Are you running any mods such as StartAllBack or Explorer Patcher? Those should be fine. I just want to have all details to try to replicate what you see.

Also, what's your exact build (⊞-R winver)?

**Comment by LesFerch** [comment]
My email is in the [user manual](https://lesferch.github.io/WinSetView/Manual.html)

**Comment by Polygon1177** [comment]
I reckon I could have found that. ; ) Sent.

**Comment by LesFerch** [comment]
Yes, I see the issue. Only on Windows 11. Very strange. I'll investigate tonight. Thanks.

**Comment by Polygon1177** [comment]
Amazing! Thanks.

**Comment by LesFerch** [comment]
Fixed in version 2.75.

Windows 11 File Explorer needed an additional FFlags entry with the registry settings for the option "Use General Items view for connected devices".
