### ISSUE TITLE
Issue: Cannot set Library grouping

### ISSUE THREAD

**Issue by PaulCoddington** [LesFerch/WinSetView#81]
Windows 11 22H2

When multiple locations are added to Libraries, a Library will by default group by those locations.

Using WinSetView to customise columns removes that grouping and appears to have no means by which to add it back.

Sometimes it is useful to blend two drives together seamlessly, sometimes it is better to keep them separate. The latter use case seems unsupported at this time.

This problem is further compounded by Sort menu in Explorer having no grouping option for Libraries either.

**Comment by LesFerch** [comment]
You can set the grouping for any folder, including Libraries, by clicking the **Columns** button. In the [manual](https://lesferch.github.io/WinSetView/Manual.html#columns), scroll down to **(⮬) (Group by)** for details. If you group a folder by **Folder path**, it will be almost the same as the Windows default. That is, it will show the folder name, followed by the folder's full path on the same line. Windows shows those items on two separate lines in Libraries. I have to do some digging to see how the two line setting is done.

**Comment by LesFerch** [comment]
I cannot replicate that behavior.  I put the same folder structure on three drives (C, E, and Q) and added those three folders to my Pictures library. I then tested group by **folder** and group by **folder path**. Both options kept the drives contents under separate headings.

Here's a screenshot of the default arrangement:
![image](https://github.com/LesFerch/WinSetView/assets/79026235/4f3278fd-1aab-47bf-9bd9-b1ccc751bacb)

Here's a screenshot of group by **folder path**:
![image](https://github.com/LesFerch/WinSetView/assets/79026235/10591062-1c2f-4ab2-a7d3-968266119450)
