### ISSUE TITLE
Missing refresh button in rightclick meru (windows11)!

### ISSUE THREAD

**Issue by dangdkhanh** [LesFerch/WinSetView#83]
![image](https://github.com/LesFerch/WinSetView/assets/99936463/3153121e-b4be-4f3c-8eb3-d49597981833)

Hi,

When export a file or save a file, sometimes I need to refresh folder.
but there is no refresh button.
please update.

**Comment by LesFerch** [comment]
What you've shown is the standard right-click menu for Windows 11. **Refresh** is under "Show more options".

If you want the classic right-click menu (which has Refresh at the top level) then you need to be sure to got to **Options** and check **Classic context menu in Windows 11**.

**Comment by dangdkhanh** [comment]
Great option. Thanks you!
