### ISSUE TITLE
White Blank Screen

### ISSUE THREAD

**Issue by vaibhav1915** [LesFerch/WinSetView#85]
White screen no menu of function showing only while blank user area also it's not responding some time even with blank screen
system :- intel i9 9th , 24gb, Windows 11 pro 22H2 build 22621.2428
![image](https://github.com/LesFerch/WinSetView/assets/37289601/9dade0a0-a9ed-4049-bbac-52d8b1cacb61)

**Comment by LesFerch** [comment]
Did you see the note at the end of the [Download Help Guide](https://lesferch.github.io/WinSetView/DownloadHelp.html) about VBScript?

**Comment by vaibhav1915** [comment]
![image](https://github.com/LesFerch/WinSetView/assets/37289601/ca333405-350b-43e6-a8d1-de62dad3b6c4)

**Comment by LesFerch** [comment]
Thanks. That confirms you don't have VBScript optional feature change yet.

Then the next possibility is that VBScript (or the entire Windows Script Host) is disabled on your computer. Is this computer managed by an IT department?

**Comment by vaibhav1915** [comment]
Nop i menage it's home personal PC
Also as long as i know i didn't change anything related to VB script disable or something from registry or polices

one more thing program opens ok but it's not responding in starting wait for few min 1 or to then just move cursor over upper screen and then scroll i get all function

**Comment by LesFerch** [comment]
Thanks. Actually, Windows Script Host is not needed. It just needs the VBScript.dll.  But let's see if you can run a simple VBScript. If you create a text file named `test.vbs` containing the line `msgbox "hi"` and double-click it, does it pop up a message box?

**Comment by vaibhav1915** [comment]
https://github.com/LesFerch/WinSetView/assets/37289601/eb4990b5-f46b-4650-afaa-033e77d5b5b7

**Comment by LesFerch** [comment]
Oh, I see! It did finally load. That happened to me once when Windows was installing an update. The CPU wasn't super busy, but my app just would not respond. Once the update was done, it was all back to normal. Check for running processes, especially Windows updates. Reboot and check again. Once things are settled, the app should load fast.

**Comment by LesFerch** [comment]
Do you have another computer you can test it on (just as a sanity check)?

**Comment by vaibhav1915** [comment]
i can check on VM
i have win7 and win 10 1909 VM server

**Comment by LesFerch** [comment]
Worth a try. It will run on 7 or 10. Win 7 has to be updated to MSHTML 11 (it comes with MSHTML 8 out of the box).

**Comment by vaibhav1915** [comment]
Same goes for win 10 1909 not check in win 7 yet will update once i boot win 7 vm

**Comment by LesFerch** [comment]
Let's see what it does tomorrow. When that happened to me I had no luck troubleshooting, so I just left it and checked the next day and it was fine. In my case, I'm sure it was connected to Windows Update, but it may be something different on your computer.

**Comment by LesFerch** [comment]
Any change today?

**Comment by vaibhav1915** [comment]
works fine in windows 10 1909 but same issue i mention eelier first white screen then not responding then need to hover over then scroll then i get all function visible

**Comment by LesFerch** [comment]
Please try it in [**Safe Mode**](https://www.elevenforum.com/t/boot-to-safe-mode-in-windows-11.538/) and let me know if that makes any difference.

**Comment by LesFerch** [comment]
Please try it in [Safe Mode](https://www.elevenforum.com/t/boot-to-safe-mode-in-windows-11.538/) and let me know if that makes any difference.

**Comment by LesFerch** [comment]
Did you try Safe Mode?

**Comment by LesFerch** [comment]
Closing due to no further communication.
