### ISSUE TITLE
Adding Audio tracks and Subtitle tracks column

### ISSUE THREAD

**Issue by wangsuki** [LesFerch/WinSetView#87]
Hi there LesFerch,

I would like to know if there is a way to add Audio tracks and Subtitle tracks column in WinSetView. I use these columns frequently for video editing MKV files.

These columns may not be from the stock Windows explorer column, but obtained after installing audio/video codec pack like K-Lite Codec Pack.

Sincere.

![Screenshot 2023-11-10 111259](https://github.com/LesFerch/WinSetView/assets/90236930/532dcf17-18fb-4960-bd3e-34b639db47ce)

**Comment by LesFerch** [comment]
I'll take a look and get back to you.

**Comment by LesFerch** [comment]
I have those properties from [Icaros](https://github.com/Xanashi/Icaros).

Here's a dump using [PropertySystemView](https://www.nirsoft.net/utils/windows_property_system_view.html):

Icaros.AudioTracks,Audio tracks,,,Yes,Yes,String,No,"{6F6B78A7-F4A2-4F9F-86B1-C6AAA6DEC9A5},4",,1638
Icaros.BitDepth,Bit depth,,,Yes,Yes,Unsigned Integer (4-Byte),No,"{306F083E-E7A8-4315-A3B6-63E9564E00B8},8",,1639
Icaros.ContainsChapters,Contains chapters,,,Yes,Yes,Boolean,No,"{3FA85462-4CB5-49F7-A8C9-A5E902BEFE90},7",,1640
Icaros.ContentCompression,Content compression,,,Yes,Yes,String,No,"{819B1E2D-989A-4346-A436-F2A8F67F19B3},6",,1641
Icaros.SubtitleGroup,Subtitles,,,Yes,Yes,Null,No,"{7CE8A423-7DE1-461D-9CB9-A9F9798FB505},7",,1642
Icaros.SubtitleTracks,Subtitle tracks,,,Yes,Yes,String,No,"{451B194C-28E4-4AFE-B3C1-2A04E616359C},5",,1643
Icaros.VideoTracks,Video tracks,,,Yes,Yes,String,No,"{EC59938F-E25E-4592-82E3-8013018EDB74},3",,1644

This will be challenging. WinSetView currently only includes System properties that are on all machines.

Providing a facility to import additional properties might be doable, but it will be a big project. I'll try to work on it this winter.

**Comment by LesFerch** [comment]
WinSetView 2.95 now includes the Icaros properties. They will be shown only if that property handler is installed.
