### ISSUE TITLE
Why is this app trying to connect to the internet?

### ISSUE THREAD

**Issue by martinandersson** [LesFerch/WinSetView#90]
I am shocked to learn the app was trying to connect to the internet during startup.

Why is that? Where is the code responsible?

**Comment by LesFerch** [comment]
It's in the source code. File `WinSetView.htm` line 392. It downloads the file `VersionHistory.md` from this repository. That's all.

Some users requested that the app indicate if a new version is available. The "Help" button changes to an "Update" button if a newer version number is found the version history file.

**Comment by LesFerch** [comment]
P.S. Sorry for the late reply. I missed the notice, but searched and there it was in my email. Weird that I didn't see it earlier.

Anyhow, thanks for what you said in the first line of your original post. That made me smile, even if it did get edited out.

**Comment by martinandersson** [comment]
lol your reply was quick. ❤️ Thank you!
