### ISSUE TITLE
Fullrow Select disable

### ISSUE THREAD

**Issue by Virgus** [LesFerch/WinSetView#92]
Hello,
thank you so much for this amazing tool !
I finally have been able to set columns as I always wanted to, instead of trying to script registry tweaks that are often unreliable.

The only thing I've not been able to change (yet) is the fullrow select which I've always hated. On W7 I managed to do it following this post: https://superuser.com/a/1083303

On W10-11 is more complex and doing it by hand messes up the shell bags and causes me continuous explorer crashes (with drag & drop and/or dealing with the trash bin). I suspect the crashes are related to messing up with shell bags but I'm not 100% sure. It's really hard to troubleshoot this issue and I ended up reinstalling the OS many times.

A tested working option would be using Ultimate Windows Tweaker 4 (for W10) and Ultimate Windows Tweaker 5 (for W11). But I dream of a scriptable solution and WinSetView seems to be capable of doing that easily.

Is there a way to your knowledge to disable FullRow select via WinSetView ?

Thanks again and
have a nice day,
V.

**Comment by LesFerch** [comment]
I looked at this once before and concluded it caused problems with other settings, but I don't recall the details. I'm taking another look at it now and I'll see if I can add an option. I did notice that the GUID {57807898-8C4F-4462-BB63-71042380B109} only shows up in Bag node entries on Windows 7 and appears to be a unused leftover (maybe from XP) because it references nothing and never appears on Windows 10 or 11.

**Comment by LesFerch** [comment]
I'm curious. I couldn't see any functional difference between full row select enabled or disabled. Is it just a cosmetic thing? For me, I like seeing the highlight all the way across. Am I missing something?

**Comment by LesFerch** [comment]
Interesting. The row spacing is tighter when full row select is enabled, especially in List view. Also, those FFLAGS enable free (temporary) arranging in Details and Icons views. At least on Windows 10. I still have to test Windows 11.

**Comment by LesFerch** [comment]
Version 2.90 is now available to download. You will see a new option:

**Legacy row and icon spacing**

Check that and then you will also see:

**Disable full row select**

See the [manual](https://lesferch.github.io/WinSetView/Manual.html#legacy-row-and-icon-spacing) for details.

**Comment by Virgus** [comment]
Amazing speed ! Thank you sooo much !!!

**Comment by LesFerch** [comment]
You're welcome. 🙂
