### ISSUE TITLE
New version tiny fix required

### ISSUE THREAD

**Issue by Virgus** [LesFerch/WinSetView#94]
Dear @LesFerch the new option to configure FullRowSelect works like a charm.

The new version though might have introduced a discrepancy (I'm using Windows 10) with the "This PC" view's configuration: what in version 2.80 was set to be "Tiles" now in version 2.91 is not shown in the same way as before. Please see the following screenshots.

![WinSetView ThisPC Tiles v2 80](https://github.com/LesFerch/WinSetView/assets/6388217/4e194ce0-6e15-4232-a30f-c060d2d7b416)
![WinSetView ThisPC Tiles v2 91](https://github.com/LesFerch/WinSetView/assets/6388217/b3f1b578-2787-4cf4-8c3b-8c9d532646e9)

Not a major issue and not an urgent one luckily.
Thanks again and kind regards,
V.

For your convenience this is the ini file I'm using for testing purposes:
[VSM.ini.txt](https://github.com/LesFerch/WinSetView/files/14073559/VSM.ini.txt)

**Comment by Virgus** [comment]
Sorry, it's not an error apparently. I just disabled the legacy row and icon spacing and the Tiles view in "This PC" came back with version 2.91. Is there any way to have both FullRow Select disabled and keep the "Tiles" view with Volumes space's details ?

Cheers,
V.

**Comment by LesFerch** [comment]
Unfortunately, "This PC" is not a unique folder type. It uses the same GUID as "General items" (aka Generic), so it's affected by any change to the Generic template. And the Tiles and Contents views are not great in the legacy spacing mode. I checked all other patches out there for "no full row select" and it's the same effect with all of them. I don't see any workaround. I recommend setting the view for "This PC" to Medium Icons or Details.

**Comment by Virgus** [comment]
Thanks again for your prompt reply.

Details view will be fine, but I wonder if there's a way to set columns size and view for "ThisPC" by script. At the end, this Details  configuration has almost the same practical result as Tiles view:
![This PC Details view](https://github.com/LesFerch/WinSetView/assets/6388217/f899bf1c-fe41-4d44-a7aa-7235d93399f1)

...or maybe it would be faster to save and restore the GUID's registry key ? Is it this the concerned one ? `HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{5C4F28B5-F869-4E84-8E60-F11DB97C5CC7}`
By using Registry workshop snapshot comparison I couldn't detect which one is the key concerned. Is it saved at logoff maybe and I should close the session to see changes ?

I'm taking advantage of this exchange to try to learn new things.

Cheers,
V.

**Comment by LesFerch** [comment]
That's the General Items GUID, so any changes to that also affect all other general items folders.

The only way to set your own custom defaults for This PC is to export its Bags reg key to a file named WinSetViewCustom.reg and drop that in WinSetView's AppData subfolder. If you keep the option "Set View for This PC" checked, WinSetView will create the following registry key for "This PC":

HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\1

Set the view as you like and repeat that for a file open/save dialog, using something like File open in Notepad, then go to RegEdit and export the above key to WinSetViewCustom.reg.

**Comment by Virgus** [comment]
Thanks @LesFerch that's amazing, worked like a charm !

To speed up the reg exporting procedure I made a batch script to save the settings after any change. I leave it here for others who might need it.

```
@ECHO off

SET "THISPCKEY=HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\1"
SET "DSTREG=WinSetViewCustom.reg"

ECHO. & ECHO  Exporting "%THISPCKEY%" & ECHO  to "%DSTREG%" & ECHO.
REG export "%THISPCKEY%" ".\AppData\%DSTREG%" /y

TIMEOUT 3 > nul
```

Cheers,
V.

**Comment by LesFerch** [comment]
You won't need that reg file anymore. I now set an FFLAGS value for "This PC" so it uses the modern view for that folder.

I only had to add one line to `WinSetView.ps1`, so I made the change and without updating the release number. If you download the package now, you'll get the updated script. Or just download and replace `WinSetView.ps1`.

**Comment by Virgus** [comment]
@LesFerch that's great, thank you so much !

Cheers,
V.
