### ISSUE TITLE
Removes Win 11 Explorer right-click menu "Show more options" - bug

### ISSUE THREAD

**Issue by Growlertiger** [LesFerch/WinSetView#96]
I ran version 2.92 on my up-to-date Win 11 system.
I found that the right-click context menu in Windows Explorer, instead of showing the short menu that ends with "Show more options" had reverted to the full list that one only sees after clicking "Show more options".

Here is a quick way to replicate the problem in WinSetView.
1. Tick next to "Reset Views to Windows Defaults"
2. Press Submit.

I realise that many people may prefer this old behaviour in Windows, but even if so, it should be a deliberate choice and should also be easily reversible.

Everything else worked perfectly.
After a search I found this page with a way to revert the problem:
[https://www.majorgeeks.com/content/page/show_more_options_11.html](url)

**Comment by LesFerch** [comment]
It's working as designed. That option only resets the default folder views to Windows defaults. As per the documentation:

"**Note**: If you use the **Reset Views to Windows Defaults** feature, be sure to check the settings under **Options**."

The same is true for others settings such as "Show file extensions" and "Enable compact view in Windows 11".

**Comment by Growlertiger** [comment]
I don't understand.
It doesn't just reset the folder views, it also changes the right-click context menu, which is nothing to do with folder views.
I didn't change any options.
I don't see any option listed that relates to the issue?

**Comment by LesFerch** [comment]
The options are preset to certain popular choices. Not all of those presets align with Windows defaults. You must click the **Options** button and verify that the options are set to what you want.

**Comment by Growlertiger** [comment]
OK, but there is no option to stop it changing this Windows default behaviour. The Options button doesn't help in this case.
And having changed it, no way to make it go back to normal Windows default behaviour.
That is why I had to search the internat for a registry change to make the right-click menu work as it should do nowadays.

**Comment by Growlertiger** [comment]
Let me try to explain better. Here is what you should see when you right-click a file in Windows Explorer.
![image](https://github.com/LesFerch/WinSetView/assets/16132925/73d29f1b-8a11-4005-936e-9abefb3152be)
After using your program, it is not possible to get back to this default state.

**Comment by LesFerch** [comment]
Uncheck this option:
![image](https://github.com/LesFerch/WinSetView/assets/79026235/a93c2474-7682-4e7f-a12d-d6c10b3b53a9)

**Comment by Growlertiger** [comment]
AH!!! Now I understand.
Thank you for your patience.
And thank you for a very helpful program.

**Comment by LesFerch** [comment]
👍🙂
