### ISSUE TITLE
This PC - no free/occupied space bar

### ISSUE THREAD

**Issue by cokolwiek235** [LesFerch/WinSetView#97]
Hello,

After using WinSetView there is no way to have regular Windows 10 This PC look.

Disabling options "Do not force standard grouping on Home / Quick Access" and "Set view for "This PC" still changes This PC view.

Looks like "Tiles" option is not there anymore, new one - "Extended tiles" replaced it, but its not the same at all.

How it looked before:
![1](https://github.com/LesFerch/WinSetView/assets/53710693/f077a455-a000-4eb0-8272-c39263a1963d)

How it looks now (best options I could come up with that remotely looks similar):
![2](https://github.com/LesFerch/WinSetView/assets/53710693/1dfbd351-0f0a-4368-87f6-4823c125aebb)

**Comment by LesFerch** [comment]
That's a side effect of enabling "Legacy row and icon spacing". Uncheck that option and you will see "This PC" return to the normal view.

**Comment by cokolwiek235** [comment]
Yes, it worked thank you. Too bad that icon spacing doesn't work with it...

I have tried using this, it kind of works, but somehow doesn't work for all folders...
```
[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
"IconSpacing"="-1125"
"IconVerticalSpacing"="-1125"
```

**Comment by LesFerch** [comment]
Yes, that setting, as the key implies, is just for the desktop. A lot of stuff that used to work in both folders and desktop was pulled by Microsoft years ago and what's left, as you saw, has some interesting limitations.

**Comment by cokolwiek235** [comment]
Actually, yeah, that reg key did the trick for explorer as well. I just had to set the explorer setting to all folders and it worked. Thank you :)

**Comment by LesFerch** [comment]
You lost me. How did you "set the explorer setting to all folders"? Are you referring to a setting in the GUI or a registry setting?

**Comment by cokolwiek235** [comment]
First did the registry, it worked for some folders, then used gui explorer setting to apply to all folders.
Also this working for me might be also related to the batches I used for explorer once when I have installed Windows... (since you are saying that its either tiles or spacing in WinSetView).

If you are interested I can send you couple batch files and reg keys I used.

**Comment by LesFerch** [comment]
Note that the button you clicked is "Apply to Folders" not "Apply to All Folders". It applies the current folder's view settings to other folders of the same _type_. That gets set to the Streams\Default key for that folder type. I wasn't aware of an option to adjust the icon spacing without changing the icon size. When you use the mouse scroll wheel in a folder, the icons increase or decrease in size with a proportional spacing adjustment. In WinSetView, that would be done by selecting one of the Icon views and then adjusting the icon size value.

Please attach you batch and reg files here. Much appreciated.

**Comment by cokolwiek235** [comment]
Ok, I was trying to do some test, and I have no idea why this works, but it works...
I am sending all reg keys and batch files I used. After applying some of them and when I used gui explorer setting to apply to folders it works...

I am sending my Win10 ini used saved with WinSetView and reg keys I used. After clearing all reg keys used in those I have used WinSetView, used 3 reg keys (Force Windows 10 to Align Icons Text to Center, Rozmiar Między Ikonami Na Pulpicie, Zmiana ustawień wyszukiwania) and it works again (and applied gui explorer setting to folders, because for some reason didn't work at first on all).

[0.zip](https://github.com/LesFerch/WinSetView/files/14466506/0.zip)
[Win10.txt](https://github.com/LesFerch/WinSetView/files/14466537/Win10.txt) - INI

Also I should mention that I use OpenShell and OldNewExplorer 1.1.9. On their own they can't to this, but maybe if those reg keys are in place they can? I will try clean install of Win10 tomorrow and test it out. Will start with WinSetView and those 3 reg keys one by one.

**Comment by LesFerch** [comment]
That's a dog's breakfast of registry hits that mostly overlap with the "Legacy row and icon spacing" option in WinSetView. Post screenshots of the end-results you want and I'll see if I can get that for you with WinSetView. Combining all of those registry entries could lead to problems. And yes, it would be good to have OpenShell and OldNewExplorer out of the equation.

**Comment by LesFerch** [comment]
Also see:

https://github.com/LesFerch/WinSetView/issues/94

**Comment by cokolwiek235** [comment]
Ok, got it down to these reg keys.

Reboot after this one:
```
[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
"IconSpacing"="-1125"
"IconVerticalSpacing"="-1125"
```

Restart explorer after this one (some folders might not be affected, you need to get to those who did get affected and apply this view in explorer settings to folders): 

```
[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{5C4F28B5-F869-4E84-8E60-F11DB97C5CC7}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{5fa96407-7e77-483c-ac93-691d05850de8}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{7d49d726-3c21-4f05-99aa-fdc2c9474656}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{94d6ddcc-4a68-4175-a374-bd584a510b78}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001

[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell\{b3690e58-e961-423b-b687-386ebfd83239}]
"FFlags"=dword:43000000
"LogicalViewMode"=dword:00000003
"Mode"=dword:00000001
```

With the second key there were also this, but might not be needed in this case:
```
[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell]
"KnownFolderDerivedFolderType"="{57807898-8C4F-4462-BB63-71042380B109}"
"SniffedFolderType"="Generic"
"FolderType"="NotSpecified"

```

**Comment by LesFerch** [comment]
I'm not seeing any difference. I'm either getting normal Windows spacing or the legacy spacing. The setting in HKCU\Control Panel\Desktop\WindowMetrics only affects the desktop for me. Please post BEFORE and AFTER  screenshots, so I know what you're looking for.

**Comment by cokolwiek235** [comment]
Sorry for late reply.

As you can see below spacing between files/folders/icons are nice and even. And as I have noticed, it doesn't work without setting up WindowMetrics.

Before:
![1](https://github.com/LesFerch/WinSetView/assets/53710693/aaf2426c-24e5-413a-b5b8-8b168d8bd1d0)

After:
![2](https://github.com/LesFerch/WinSetView/assets/53710693/bd335764-f233-4558-9c2b-0df563771c8c)

**Comment by LesFerch** [comment]
So, it's a row spacing issue. As I see it, the columns are lined up the same in both screenshots. The difference is that, in the first screenshot, whenever a file name wraps around to three lines, it causes the row spacing to increase. In the second screenshot, all file names are cut off at two lines, keeping the row spacing consistent.

I'll run some tests to see if any WindowMetrics have any effect, but I can tell you for sure that selecting "Legacy row and icon spacing" in WinSetView will give you the consistent row spacing.

**Comment by LesFerch** [comment]
Yes, when "Legacy row and icon spacing" is enabled, the WindowMetrics settings effect folders as well as the desktop. A logout\login is required to see the change. Restarting Explorer is not enough.

So, if you check "Legacy row and icon spacing" in WinSetView and make your desired spacing adjustments in WindowMetrics, you should not need any of those other reg or bat files.

I could, possibly, add a GUI control to set the spacing when "Legacy row and icon spacing" is checked, but it's a lot of trouble for a setting that is deprecated and isn't compatible with dark mode.

Is there anything other than the spacing?

**Comment by cokolwiek235** [comment]
Well, this issue originally was about view in This PC, and since setting "Legacy row and icon spacing" was causing problems with it, this is my way around.

**Comment by LesFerch** [comment]
If I understand correctly, you've kept the new view style for "This PC", but also enabled legacy spacing for certain folder types. Since "This PC" uses the General Items GUID, my guess is that you do not have legacy spacing enabled for General Items. Is that correct?

What is the folder type for the screenshot you posted? I'm guessing it's type is Music.

**Comment by cokolwiek235** [comment]
Well, this folder in screenshots is set as general.

**Comment by LesFerch** [comment]
Thanks. I'll have to do more testing to figure out exactly what's going on.

**Comment by LesFerch** [comment]
OK, I see what's happening now. You've forced This PC to use the modern folder view mode with everything else in the legacy mode. To get the same result in WinSetView, all you need is to a file named `WinSetViewCustom.reg` to WinSetView's `AppData` folder, containing this code:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\1\Shell\{5C4F28B5-F869-4E84-8E60-F11DB97C5CC7}]
"FFlags"=dword:41200001
```
That should give you the same result as you have now. I'll probably make that the default in the next update.

**Comment by LesFerch** [comment]
I only had to add one line to `WinSetView.ps1` so I made the change and without updating the release number. If you download the package now, you'll get the updated script. Or just download and replace `WinSetView.ps1` .

**Comment by cokolwiek235** [comment]
Great, thank you!
But since it works now for me, I won't test it. Don't want to mess up the current settings. (Unless you really want me too :smile: )

**Comment by LesFerch** [comment]
I'd really appreciate it. I'm confident it will be correct and you won't have to do any "Apply to Folders".

**Comment by cokolwiek235** [comment]
Tried it out, works exactly like it did before:

With Legacy row and icon spacing off, space between rows is bigger, This PC remains the same.
With Legacy row and icon spacing on, space between rows is always the same - nice and even, This PC doesn't even show tiles view setting.

**Comment by cokolwiek235** [comment]
Oh, checked Set View for This PC in settinfs to Tiles and it works :)

**Comment by LesFerch** [comment]
Thank you so much for testing! Yes, I should have mentioned that in order to force This PC to use the modern view, "Set View for This PC" must be checked. 🙂

**Comment by cokolwiek235** [comment]
Thank you so much for implementing it, and for your time :)
