### ISSUE TITLE
How to revert everything?

### ISSUE THREAD

**Issue by lucellent** [LesFerch/WinSetView#99]
I tried it out but personally this isn't for me. I was able to manually revert some of the changes but others I have no clue how to (and there aren't options in the app)

So how does one revert everything to how it was prior to WinSetView?

**Comment by LesFerch** [comment]
You can use the Restore button to restore the views to a previous state. And be sure to set the items under Options to your preferences. Those are separate from Restore.

But I really don't understand why you don't just move forward. WinSetView isn't a new way of working. It just sets defaults for you. The best course of action is to set the defaults as you like and then, for any folders you want different than the defaults, just set those folders manually in Explorer.

My experience is that people who are confused by the process are thinking in terms of specific folders and not folder TYPES . Those items listed in WinSetView, such as "Pictures" represent folder types, not individual folders.

**Comment by ljwobker** [comment]
I found this last comment particularly helpful -- "think in terms of folder types not folders" ... I don't know exactly how I would try to phrase it, but I feel like having these sorts of "philosophical-level" guidelines or explanations very near the top of the howto/docs/manual/whatever might pay dividends....?

**Comment by LesFerch** [comment]
Good point. The documentation is always evolving. I'll take a look at adding something like this. Thanks.
